{-# LANGUAGE DeriveGeneric     #-}
{-# LANGUAGE DeriveAnyClass    #-}
{-# LANGUAGE DataKinds         #-}
{-# LANGUAGE GADTs             #-}
{-# LANGUAGE TypeApplications  #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing #-}
{-# OPTIONS_GHC -fno-warn-unused-matches #-}

-- | Generated by Haskell protocol buffer compiler. DO NOT EDIT!
module Euler.Proto.Event.Customer where
import qualified Prelude as Hs
import qualified Proto3.Suite.Class as HsProtobuf
import qualified Proto3.Suite.DotProto as HsProtobuf
import qualified Proto3.Suite.JSONPB as HsJSONPB
import Proto3.Suite.JSONPB ((.=), (.:))
import qualified Proto3.Suite.Types as HsProtobuf
import qualified Proto3.Wire as HsProtobuf
import qualified Control.Applicative as Hs
import Control.Applicative ((<*>), (<|>), (<$>))
import qualified Control.DeepSeq as Hs
import qualified Control.Monad as Hs
import qualified Data.ByteString as Hs
import qualified Data.Coerce as Hs
import qualified Data.Int as Hs (Int16, Int32, Int64)
import qualified Data.List.NonEmpty as Hs (NonEmpty(..))
import qualified Data.Map as Hs (Map, mapKeysMonotonic)
import qualified Data.Proxy as Proxy
import qualified Data.String as Hs (fromString)
import qualified Data.Text.Lazy as Hs (Text)
import qualified Data.Vector as Hs (Vector)
import qualified Data.Word as Hs (Word16, Word32, Word64)
import qualified GHC.Enum as Hs
import qualified GHC.Generics as Hs
import qualified Unsafe.Coerce as Hs
 
data Customer = Customer{customerId :: Hs.Text,
                         customerVersion :: Hs.Int64, customerDateCreated :: Hs.Int64,
                         customerEmailAddress :: Hs.Text, customerFirstName :: Hs.Text,
                         customerLastName :: Hs.Text, customerLastUpdated :: Hs.Int64,
                         customerMerchantAccountId :: Hs.Int64,
                         customerMobileCountryCode :: Hs.Text,
                         customerMobileNumber :: Hs.Text,
                         customerObjectReferenceId :: Hs.Text,
                         customerCustomerEventType ::
                         HsProtobuf.Enumerated Euler.Proto.Event.Customer.CustomerEventType}
              deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic, Hs.NFData)
 
instance HsProtobuf.Named Customer where
        nameOf _ = (Hs.fromString "Customer")
 
instance HsProtobuf.HasDefault Customer
 
instance HsProtobuf.Message Customer where
        encodeMessage _
          Customer{customerId = customerId,
                   customerVersion = customerVersion,
                   customerDateCreated = customerDateCreated,
                   customerEmailAddress = customerEmailAddress,
                   customerFirstName = customerFirstName,
                   customerLastName = customerLastName,
                   customerLastUpdated = customerLastUpdated,
                   customerMerchantAccountId = customerMerchantAccountId,
                   customerMobileCountryCode = customerMobileCountryCode,
                   customerMobileNumber = customerMobileNumber,
                   customerObjectReferenceId = customerObjectReferenceId,
                   customerCustomerEventType = customerCustomerEventType}
          = (Hs.mconcat
               [(HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 1)
                   customerId),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 2)
                   customerVersion),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 3)
                   customerDateCreated),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 4)
                   customerEmailAddress),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 5)
                   customerFirstName),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 6)
                   customerLastName),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 7)
                   customerLastUpdated),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 8)
                   customerMerchantAccountId),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 9)
                   customerMobileCountryCode),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 10)
                   customerMobileNumber),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 11)
                   customerObjectReferenceId),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 12)
                   customerCustomerEventType)])
        decodeMessage _
          = (Hs.pure Customer) <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 1))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 2))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 3))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 4))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 5))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 6))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 7))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 8))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 9))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 10))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 11))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 12))
        dotProto _
          = [(HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 1)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "id")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 2)
                (HsProtobuf.Prim HsProtobuf.Int64)
                (HsProtobuf.Single "version")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 3)
                (HsProtobuf.Prim HsProtobuf.Int64)
                (HsProtobuf.Single "date_created")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 4)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "email_address")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 5)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "first_name")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 6)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "last_name")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 7)
                (HsProtobuf.Prim HsProtobuf.Int64)
                (HsProtobuf.Single "last_updated")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 8)
                (HsProtobuf.Prim HsProtobuf.Int64)
                (HsProtobuf.Single "merchant_account_id")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 9)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "mobile_country_code")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 10)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "mobile_number")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 11)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "object_reference_id")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 12)
                (HsProtobuf.Prim
                   (HsProtobuf.Named (HsProtobuf.Single "CustomerEventType")))
                (HsProtobuf.Single "customer_event_type")
                []
                "")]
 
instance HsJSONPB.ToJSONPB Customer where
        toJSONPB (Customer f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12)
          = (HsJSONPB.object
               ["id" .= f1, "version" .= f2, "date_created" .= f3,
                "email_address" .= f4, "first_name" .= f5, "last_name" .= f6,
                "last_updated" .= f7, "merchant_account_id" .= f8,
                "mobile_country_code" .= f9, "mobile_number" .= f10,
                "object_reference_id" .= f11, "customer_event_type" .= f12])
        toEncodingPB (Customer f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12)
          = (HsJSONPB.pairs
               ["id" .= f1, "version" .= f2, "date_created" .= f3,
                "email_address" .= f4, "first_name" .= f5, "last_name" .= f6,
                "last_updated" .= f7, "merchant_account_id" .= f8,
                "mobile_country_code" .= f9, "mobile_number" .= f10,
                "object_reference_id" .= f11, "customer_event_type" .= f12])
 
instance HsJSONPB.FromJSONPB Customer where
        parseJSONPB
          = (HsJSONPB.withObject "Customer"
               (\ obj ->
                  (Hs.pure Customer) <*> obj .: "id" <*> obj .: "version" <*>
                    obj .: "date_created"
                    <*> obj .: "email_address"
                    <*> obj .: "first_name"
                    <*> obj .: "last_name"
                    <*> obj .: "last_updated"
                    <*> obj .: "merchant_account_id"
                    <*> obj .: "mobile_country_code"
                    <*> obj .: "mobile_number"
                    <*> obj .: "object_reference_id"
                    <*> obj .: "customer_event_type"))
 
instance HsJSONPB.ToJSON Customer where
        toJSON = HsJSONPB.toAesonValue
        toEncoding = HsJSONPB.toAesonEncoding
 
instance HsJSONPB.FromJSON Customer where
        parseJSON = HsJSONPB.parseJSONPB
 
instance HsJSONPB.ToSchema Customer where
        declareNamedSchema _
          = do let declare_id = HsJSONPB.declareSchemaRef
               customerId <- declare_id Proxy.Proxy
               let declare_version = HsJSONPB.declareSchemaRef
               customerVersion <- declare_version Proxy.Proxy
               let declare_date_created = HsJSONPB.declareSchemaRef
               customerDateCreated <- declare_date_created Proxy.Proxy
               let declare_email_address = HsJSONPB.declareSchemaRef
               customerEmailAddress <- declare_email_address Proxy.Proxy
               let declare_first_name = HsJSONPB.declareSchemaRef
               customerFirstName <- declare_first_name Proxy.Proxy
               let declare_last_name = HsJSONPB.declareSchemaRef
               customerLastName <- declare_last_name Proxy.Proxy
               let declare_last_updated = HsJSONPB.declareSchemaRef
               customerLastUpdated <- declare_last_updated Proxy.Proxy
               let declare_merchant_account_id = HsJSONPB.declareSchemaRef
               customerMerchantAccountId <- declare_merchant_account_id
                                              Proxy.Proxy
               let declare_mobile_country_code = HsJSONPB.declareSchemaRef
               customerMobileCountryCode <- declare_mobile_country_code
                                              Proxy.Proxy
               let declare_mobile_number = HsJSONPB.declareSchemaRef
               customerMobileNumber <- declare_mobile_number Proxy.Proxy
               let declare_object_reference_id = HsJSONPB.declareSchemaRef
               customerObjectReferenceId <- declare_object_reference_id
                                              Proxy.Proxy
               let declare_customer_event_type = HsJSONPB.declareSchemaRef
               customerCustomerEventType <- declare_customer_event_type
                                              Proxy.Proxy
               let _ = Hs.pure Customer <*> HsJSONPB.asProxy declare_id <*>
                         HsJSONPB.asProxy declare_version
                         <*> HsJSONPB.asProxy declare_date_created
                         <*> HsJSONPB.asProxy declare_email_address
                         <*> HsJSONPB.asProxy declare_first_name
                         <*> HsJSONPB.asProxy declare_last_name
                         <*> HsJSONPB.asProxy declare_last_updated
                         <*> HsJSONPB.asProxy declare_merchant_account_id
                         <*> HsJSONPB.asProxy declare_mobile_country_code
                         <*> HsJSONPB.asProxy declare_mobile_number
                         <*> HsJSONPB.asProxy declare_object_reference_id
                         <*> HsJSONPB.asProxy declare_customer_event_type
               Hs.return
                 (HsJSONPB.NamedSchema{HsJSONPB._namedSchemaName =
                                         Hs.Just "Customer",
                                       HsJSONPB._namedSchemaSchema =
                                         Hs.mempty{HsJSONPB._schemaParamSchema =
                                                     Hs.mempty{HsJSONPB._paramSchemaType =
                                                                 Hs.Just HsJSONPB.SwaggerObject},
                                                   HsJSONPB._schemaProperties =
                                                     HsJSONPB.insOrdFromList
                                                       [("id", customerId),
                                                        ("version", customerVersion),
                                                        ("date_created", customerDateCreated),
                                                        ("email_address", customerEmailAddress),
                                                        ("first_name", customerFirstName),
                                                        ("last_name", customerLastName),
                                                        ("last_updated", customerLastUpdated),
                                                        ("merchant_account_id",
                                                         customerMerchantAccountId),
                                                        ("mobile_country_code",
                                                         customerMobileCountryCode),
                                                        ("mobile_number", customerMobileNumber),
                                                        ("object_reference_id",
                                                         customerObjectReferenceId),
                                                        ("customer_event_type",
                                                         customerCustomerEventType)]}})
 
data CustomerEventType = CustomerEventTypeNO_CUSTOMER_EVENT_TYPE
                       | CustomerEventTypeCUSTOMER_EVENT_CREATE
                       | CustomerEventTypeCUSTOMER_EVENT_UPDATE
                       deriving (Hs.Show, Hs.Eq, Hs.Generic, Hs.NFData)
 
instance HsProtobuf.Named CustomerEventType where
        nameOf _ = (Hs.fromString "CustomerEventType")
 
instance HsProtobuf.HasDefault CustomerEventType
 
instance Hs.Bounded CustomerEventType where
        minBound = CustomerEventTypeNO_CUSTOMER_EVENT_TYPE
        maxBound = CustomerEventTypeCUSTOMER_EVENT_UPDATE
 
instance Hs.Ord CustomerEventType where
        compare x y
          = Hs.compare (HsProtobuf.fromProtoEnum x)
              (HsProtobuf.fromProtoEnum y)
 
instance HsProtobuf.ProtoEnum CustomerEventType where
        toProtoEnumMay 0 = Hs.Just CustomerEventTypeNO_CUSTOMER_EVENT_TYPE
        toProtoEnumMay 1 = Hs.Just CustomerEventTypeCUSTOMER_EVENT_CREATE
        toProtoEnumMay 2 = Hs.Just CustomerEventTypeCUSTOMER_EVENT_UPDATE
        toProtoEnumMay _ = Hs.Nothing
        fromProtoEnum (CustomerEventTypeNO_CUSTOMER_EVENT_TYPE) = 0
        fromProtoEnum (CustomerEventTypeCUSTOMER_EVENT_CREATE) = 1
        fromProtoEnum (CustomerEventTypeCUSTOMER_EVENT_UPDATE) = 2
 
instance HsJSONPB.ToJSONPB CustomerEventType where
        toJSONPB x _ = HsJSONPB.enumFieldString x
        toEncodingPB x _ = HsJSONPB.enumFieldEncoding x
 
instance HsJSONPB.FromJSONPB CustomerEventType where
        parseJSONPB (HsJSONPB.String "NO_CUSTOMER_EVENT_TYPE")
          = Hs.pure CustomerEventTypeNO_CUSTOMER_EVENT_TYPE
        parseJSONPB (HsJSONPB.String "CUSTOMER_EVENT_CREATE")
          = Hs.pure CustomerEventTypeCUSTOMER_EVENT_CREATE
        parseJSONPB (HsJSONPB.String "CUSTOMER_EVENT_UPDATE")
          = Hs.pure CustomerEventTypeCUSTOMER_EVENT_UPDATE
        parseJSONPB v = (HsJSONPB.typeMismatch "CustomerEventType" v)
 
instance HsJSONPB.ToJSON CustomerEventType where
        toJSON = HsJSONPB.toAesonValue
        toEncoding = HsJSONPB.toAesonEncoding
 
instance HsJSONPB.FromJSON CustomerEventType where
        parseJSON = HsJSONPB.parseJSONPB
 
instance HsProtobuf.Finite CustomerEventType