{-# LANGUAGE DeriveGeneric     #-}
{-# LANGUAGE DeriveAnyClass    #-}
{-# LANGUAGE DataKinds         #-}
{-# LANGUAGE GADTs             #-}
{-# LANGUAGE TypeApplications  #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing #-}
{-# OPTIONS_GHC -fno-warn-unused-matches #-}

-- | Generated by Haskell protocol buffer compiler. DO NOT EDIT!
module Euler.Proto.Event.Order where
import qualified Prelude as Hs
import qualified Proto3.Suite.Class as HsProtobuf
import qualified Proto3.Suite.DotProto as HsProtobuf
import qualified Proto3.Suite.JSONPB as HsJSONPB
import Proto3.Suite.JSONPB ((.=), (.:))
import qualified Proto3.Suite.Types as HsProtobuf
import qualified Proto3.Wire as HsProtobuf
import qualified Control.Applicative as Hs
import Control.Applicative ((<*>), (<|>), (<$>))
import qualified Control.DeepSeq as Hs
import qualified Control.Monad as Hs
import qualified Data.ByteString as Hs
import qualified Data.Coerce as Hs
import qualified Data.Int as Hs (Int16, Int32, Int64)
import qualified Data.List.NonEmpty as Hs (NonEmpty(..))
import qualified Data.Map as Hs (Map, mapKeysMonotonic)
import qualified Data.Proxy as Proxy
import qualified Data.String as Hs (fromString)
import qualified Data.Text.Lazy as Hs (Text)
import qualified Data.Vector as Hs (Vector)
import qualified Data.Word as Hs (Word16, Word32, Word64)
import qualified GHC.Enum as Hs
import qualified GHC.Generics as Hs
import qualified Unsafe.Coerce as Hs
 
data Order = Order{orderId :: Hs.Int64, orderVersion :: Hs.Int64,
                   orderAmount :: Hs.Double,
                   orderCurrency ::
                   HsProtobuf.Enumerated Euler.Proto.Event.Order.Currency,
                   orderMerchantId :: Hs.Text, orderOrderId :: Hs.Text,
                   orderOrderUuid :: Hs.Text,
                   orderOrderType ::
                   HsProtobuf.Enumerated Euler.Proto.Event.Order.OrderType,
                   orderOrderStatus ::
                   HsProtobuf.Enumerated Euler.Proto.Event.Order.OrderStatus,
                   orderCustomerId :: Hs.Text, orderCustomerEmail :: Hs.Text,
                   orderCustomerPhone :: Hs.Text, orderBillingAddressId :: Hs.Int64,
                   orderShippingAddressId :: Hs.Int64,
                   orderUdf :: Hs.Maybe Euler.Proto.Event.Order.UDF,
                   orderDescription :: Hs.Text, orderReturnUrl :: Hs.Text,
                   orderAmountRefunded :: Hs.Double, orderRefundedEntirely :: Hs.Bool,
                   orderProductId :: Hs.Text,
                   orderMandate ::
                   HsProtobuf.Enumerated Euler.Proto.Event.Order.MandateFeature,
                   orderLastSynced :: Hs.Int64, orderDateCreated :: Hs.Int64,
                   orderLastModified :: Hs.Int64,
                   orderOrderEventType ::
                   HsProtobuf.Enumerated Euler.Proto.Event.Order.OrderEventType}
           deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic, Hs.NFData)
 
instance HsProtobuf.Named Order where
        nameOf _ = (Hs.fromString "Order")
 
instance HsProtobuf.HasDefault Order
 
instance HsProtobuf.Message Order where
        encodeMessage _
          Order{orderId = orderId, orderVersion = orderVersion,
                orderAmount = orderAmount, orderCurrency = orderCurrency,
                orderMerchantId = orderMerchantId, orderOrderId = orderOrderId,
                orderOrderUuid = orderOrderUuid, orderOrderType = orderOrderType,
                orderOrderStatus = orderOrderStatus,
                orderCustomerId = orderCustomerId,
                orderCustomerEmail = orderCustomerEmail,
                orderCustomerPhone = orderCustomerPhone,
                orderBillingAddressId = orderBillingAddressId,
                orderShippingAddressId = orderShippingAddressId,
                orderUdf = orderUdf, orderDescription = orderDescription,
                orderReturnUrl = orderReturnUrl,
                orderAmountRefunded = orderAmountRefunded,
                orderRefundedEntirely = orderRefundedEntirely,
                orderProductId = orderProductId, orderMandate = orderMandate,
                orderLastSynced = orderLastSynced,
                orderDateCreated = orderDateCreated,
                orderLastModified = orderLastModified,
                orderOrderEventType = orderOrderEventType}
          = (Hs.mconcat
               [(HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 1)
                   orderId),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 2)
                   orderVersion),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 3)
                   orderAmount),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 4)
                   orderCurrency),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 5)
                   orderMerchantId),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 6)
                   orderOrderId),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 7)
                   orderOrderUuid),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 8)
                   orderOrderType),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 9)
                   orderOrderStatus),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 10)
                   orderCustomerId),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 11)
                   orderCustomerEmail),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 12)
                   orderCustomerPhone),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 13)
                   orderBillingAddressId),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 14)
                   orderShippingAddressId),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 15)
                   (Hs.coerce @(Hs.Maybe Euler.Proto.Event.Order.UDF)
                      @(HsProtobuf.Nested Euler.Proto.Event.Order.UDF)
                      orderUdf)),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 16)
                   orderDescription),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 17)
                   orderReturnUrl),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 18)
                   orderAmountRefunded),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 19)
                   orderRefundedEntirely),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 20)
                   orderProductId),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 21)
                   orderMandate),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 22)
                   orderLastSynced),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 23)
                   orderDateCreated),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 24)
                   orderLastModified),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 25)
                   orderOrderEventType)])
        decodeMessage _
          = (Hs.pure Order) <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 1))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 2))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 3))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 4))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 5))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 6))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 7))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 8))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 9))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 10))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 11))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 12))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 13))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 14))
              <*>
              (Hs.coerce @(_ (HsProtobuf.Nested Euler.Proto.Event.Order.UDF))
                 @(_ (Hs.Maybe Euler.Proto.Event.Order.UDF))
                 (HsProtobuf.at HsProtobuf.decodeMessageField
                    (HsProtobuf.FieldNumber 15)))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 16))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 17))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 18))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 19))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 20))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 21))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 22))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 23))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 24))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 25))
        dotProto _
          = [(HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 1)
                (HsProtobuf.Prim HsProtobuf.Int64)
                (HsProtobuf.Single "id")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 2)
                (HsProtobuf.Prim HsProtobuf.Int64)
                (HsProtobuf.Single "version")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 3)
                (HsProtobuf.Prim HsProtobuf.Double)
                (HsProtobuf.Single "amount")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 4)
                (HsProtobuf.Prim (HsProtobuf.Named (HsProtobuf.Single "Currency")))
                (HsProtobuf.Single "currency")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 5)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "merchant_id")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 6)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "order_id")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 7)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "order_uuid")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 8)
                (HsProtobuf.Prim
                   (HsProtobuf.Named (HsProtobuf.Single "OrderType")))
                (HsProtobuf.Single "order_type")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 9)
                (HsProtobuf.Prim
                   (HsProtobuf.Named (HsProtobuf.Single "OrderStatus")))
                (HsProtobuf.Single "order_status")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 10)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "customer_id")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 11)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "customer_email")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 12)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "customer_phone")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 13)
                (HsProtobuf.Prim HsProtobuf.Int64)
                (HsProtobuf.Single "billing_address_id")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 14)
                (HsProtobuf.Prim HsProtobuf.Int64)
                (HsProtobuf.Single "shipping_address_id")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 15)
                (HsProtobuf.Prim (HsProtobuf.Named (HsProtobuf.Single "UDF")))
                (HsProtobuf.Single "udf")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 16)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "description")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 17)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "return_url")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 18)
                (HsProtobuf.Prim HsProtobuf.Double)
                (HsProtobuf.Single "amount_refunded")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 19)
                (HsProtobuf.Prim HsProtobuf.Bool)
                (HsProtobuf.Single "refunded_entirely")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 20)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "product_id")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 21)
                (HsProtobuf.Prim
                   (HsProtobuf.Named (HsProtobuf.Single "MandateFeature")))
                (HsProtobuf.Single "mandate")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 22)
                (HsProtobuf.Prim HsProtobuf.Int64)
                (HsProtobuf.Single "last_synced")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 23)
                (HsProtobuf.Prim HsProtobuf.Int64)
                (HsProtobuf.Single "date_created")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 24)
                (HsProtobuf.Prim HsProtobuf.Int64)
                (HsProtobuf.Single "last_modified")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 25)
                (HsProtobuf.Prim
                   (HsProtobuf.Named (HsProtobuf.Single "OrderEventType")))
                (HsProtobuf.Single "order_event_type")
                []
                "")]
 
instance HsJSONPB.ToJSONPB Order where
        toJSONPB
          (Order f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14 f15 f16 f17
             f18 f19 f20 f21 f22 f23 f24 f25)
          = (HsJSONPB.object
               ["id" .= f1, "version" .= f2, "amount" .= f3, "currency" .= f4,
                "merchant_id" .= f5, "order_id" .= f6, "order_uuid" .= f7,
                "order_type" .= f8, "order_status" .= f9, "customer_id" .= f10,
                "customer_email" .= f11, "customer_phone" .= f12,
                "billing_address_id" .= f13, "shipping_address_id" .= f14,
                "udf" .= f15, "description" .= f16, "return_url" .= f17,
                "amount_refunded" .= f18, "refunded_entirely" .= f19,
                "product_id" .= f20, "mandate" .= f21, "last_synced" .= f22,
                "date_created" .= f23, "last_modified" .= f24,
                "order_event_type" .= f25])
        toEncodingPB
          (Order f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14 f15 f16 f17
             f18 f19 f20 f21 f22 f23 f24 f25)
          = (HsJSONPB.pairs
               ["id" .= f1, "version" .= f2, "amount" .= f3, "currency" .= f4,
                "merchant_id" .= f5, "order_id" .= f6, "order_uuid" .= f7,
                "order_type" .= f8, "order_status" .= f9, "customer_id" .= f10,
                "customer_email" .= f11, "customer_phone" .= f12,
                "billing_address_id" .= f13, "shipping_address_id" .= f14,
                "udf" .= f15, "description" .= f16, "return_url" .= f17,
                "amount_refunded" .= f18, "refunded_entirely" .= f19,
                "product_id" .= f20, "mandate" .= f21, "last_synced" .= f22,
                "date_created" .= f23, "last_modified" .= f24,
                "order_event_type" .= f25])
 
instance HsJSONPB.FromJSONPB Order where
        parseJSONPB
          = (HsJSONPB.withObject "Order"
               (\ obj ->
                  (Hs.pure Order) <*> obj .: "id" <*> obj .: "version" <*>
                    obj .: "amount"
                    <*> obj .: "currency"
                    <*> obj .: "merchant_id"
                    <*> obj .: "order_id"
                    <*> obj .: "order_uuid"
                    <*> obj .: "order_type"
                    <*> obj .: "order_status"
                    <*> obj .: "customer_id"
                    <*> obj .: "customer_email"
                    <*> obj .: "customer_phone"
                    <*> obj .: "billing_address_id"
                    <*> obj .: "shipping_address_id"
                    <*> obj .: "udf"
                    <*> obj .: "description"
                    <*> obj .: "return_url"
                    <*> obj .: "amount_refunded"
                    <*> obj .: "refunded_entirely"
                    <*> obj .: "product_id"
                    <*> obj .: "mandate"
                    <*> obj .: "last_synced"
                    <*> obj .: "date_created"
                    <*> obj .: "last_modified"
                    <*> obj .: "order_event_type"))
 
instance HsJSONPB.ToJSON Order where
        toJSON = HsJSONPB.toAesonValue
        toEncoding = HsJSONPB.toAesonEncoding
 
instance HsJSONPB.FromJSON Order where
        parseJSON = HsJSONPB.parseJSONPB
 
instance HsJSONPB.ToSchema Order where
        declareNamedSchema _
          = do let declare_id = HsJSONPB.declareSchemaRef
               orderId <- declare_id Proxy.Proxy
               let declare_version = HsJSONPB.declareSchemaRef
               orderVersion <- declare_version Proxy.Proxy
               let declare_amount = HsJSONPB.declareSchemaRef
               orderAmount <- declare_amount Proxy.Proxy
               let declare_currency = HsJSONPB.declareSchemaRef
               orderCurrency <- declare_currency Proxy.Proxy
               let declare_merchant_id = HsJSONPB.declareSchemaRef
               orderMerchantId <- declare_merchant_id Proxy.Proxy
               let declare_order_id = HsJSONPB.declareSchemaRef
               orderOrderId <- declare_order_id Proxy.Proxy
               let declare_order_uuid = HsJSONPB.declareSchemaRef
               orderOrderUuid <- declare_order_uuid Proxy.Proxy
               let declare_order_type = HsJSONPB.declareSchemaRef
               orderOrderType <- declare_order_type Proxy.Proxy
               let declare_order_status = HsJSONPB.declareSchemaRef
               orderOrderStatus <- declare_order_status Proxy.Proxy
               let declare_customer_id = HsJSONPB.declareSchemaRef
               orderCustomerId <- declare_customer_id Proxy.Proxy
               let declare_customer_email = HsJSONPB.declareSchemaRef
               orderCustomerEmail <- declare_customer_email Proxy.Proxy
               let declare_customer_phone = HsJSONPB.declareSchemaRef
               orderCustomerPhone <- declare_customer_phone Proxy.Proxy
               let declare_billing_address_id = HsJSONPB.declareSchemaRef
               orderBillingAddressId <- declare_billing_address_id Proxy.Proxy
               let declare_shipping_address_id = HsJSONPB.declareSchemaRef
               orderShippingAddressId <- declare_shipping_address_id Proxy.Proxy
               let declare_udf = HsJSONPB.declareSchemaRef
               orderUdf <- declare_udf Proxy.Proxy
               let declare_description = HsJSONPB.declareSchemaRef
               orderDescription <- declare_description Proxy.Proxy
               let declare_return_url = HsJSONPB.declareSchemaRef
               orderReturnUrl <- declare_return_url Proxy.Proxy
               let declare_amount_refunded = HsJSONPB.declareSchemaRef
               orderAmountRefunded <- declare_amount_refunded Proxy.Proxy
               let declare_refunded_entirely = HsJSONPB.declareSchemaRef
               orderRefundedEntirely <- declare_refunded_entirely Proxy.Proxy
               let declare_product_id = HsJSONPB.declareSchemaRef
               orderProductId <- declare_product_id Proxy.Proxy
               let declare_mandate = HsJSONPB.declareSchemaRef
               orderMandate <- declare_mandate Proxy.Proxy
               let declare_last_synced = HsJSONPB.declareSchemaRef
               orderLastSynced <- declare_last_synced Proxy.Proxy
               let declare_date_created = HsJSONPB.declareSchemaRef
               orderDateCreated <- declare_date_created Proxy.Proxy
               let declare_last_modified = HsJSONPB.declareSchemaRef
               orderLastModified <- declare_last_modified Proxy.Proxy
               let declare_order_event_type = HsJSONPB.declareSchemaRef
               orderOrderEventType <- declare_order_event_type Proxy.Proxy
               let _ = Hs.pure Order <*> HsJSONPB.asProxy declare_id <*>
                         HsJSONPB.asProxy declare_version
                         <*> HsJSONPB.asProxy declare_amount
                         <*> HsJSONPB.asProxy declare_currency
                         <*> HsJSONPB.asProxy declare_merchant_id
                         <*> HsJSONPB.asProxy declare_order_id
                         <*> HsJSONPB.asProxy declare_order_uuid
                         <*> HsJSONPB.asProxy declare_order_type
                         <*> HsJSONPB.asProxy declare_order_status
                         <*> HsJSONPB.asProxy declare_customer_id
                         <*> HsJSONPB.asProxy declare_customer_email
                         <*> HsJSONPB.asProxy declare_customer_phone
                         <*> HsJSONPB.asProxy declare_billing_address_id
                         <*> HsJSONPB.asProxy declare_shipping_address_id
                         <*> HsJSONPB.asProxy declare_udf
                         <*> HsJSONPB.asProxy declare_description
                         <*> HsJSONPB.asProxy declare_return_url
                         <*> HsJSONPB.asProxy declare_amount_refunded
                         <*> HsJSONPB.asProxy declare_refunded_entirely
                         <*> HsJSONPB.asProxy declare_product_id
                         <*> HsJSONPB.asProxy declare_mandate
                         <*> HsJSONPB.asProxy declare_last_synced
                         <*> HsJSONPB.asProxy declare_date_created
                         <*> HsJSONPB.asProxy declare_last_modified
                         <*> HsJSONPB.asProxy declare_order_event_type
               Hs.return
                 (HsJSONPB.NamedSchema{HsJSONPB._namedSchemaName = Hs.Just "Order",
                                       HsJSONPB._namedSchemaSchema =
                                         Hs.mempty{HsJSONPB._schemaParamSchema =
                                                     Hs.mempty{HsJSONPB._paramSchemaType =
                                                                 Hs.Just HsJSONPB.SwaggerObject},
                                                   HsJSONPB._schemaProperties =
                                                     HsJSONPB.insOrdFromList
                                                       [("id", orderId), ("version", orderVersion),
                                                        ("amount", orderAmount),
                                                        ("currency", orderCurrency),
                                                        ("merchant_id", orderMerchantId),
                                                        ("order_id", orderOrderId),
                                                        ("order_uuid", orderOrderUuid),
                                                        ("order_type", orderOrderType),
                                                        ("order_status", orderOrderStatus),
                                                        ("customer_id", orderCustomerId),
                                                        ("customer_email", orderCustomerEmail),
                                                        ("customer_phone", orderCustomerPhone),
                                                        ("billing_address_id",
                                                         orderBillingAddressId),
                                                        ("shipping_address_id",
                                                         orderShippingAddressId),
                                                        ("udf", orderUdf),
                                                        ("description", orderDescription),
                                                        ("return_url", orderReturnUrl),
                                                        ("amount_refunded", orderAmountRefunded),
                                                        ("refunded_entirely",
                                                         orderRefundedEntirely),
                                                        ("product_id", orderProductId),
                                                        ("mandate", orderMandate),
                                                        ("last_synced", orderLastSynced),
                                                        ("date_created", orderDateCreated),
                                                        ("last_modified", orderLastModified),
                                                        ("order_event_type",
                                                         orderOrderEventType)]}})
 
data Currency = CurrencyNO_CURRENCY
              | CurrencyINR
              | CurrencyUSD
              | CurrencyGBP
              | CurrencyEUR
              | CurrencyAED
              deriving (Hs.Show, Hs.Eq, Hs.Generic, Hs.NFData)
 
instance HsProtobuf.Named Currency where
        nameOf _ = (Hs.fromString "Currency")
 
instance HsProtobuf.HasDefault Currency
 
instance Hs.Bounded Currency where
        minBound = CurrencyNO_CURRENCY
        maxBound = CurrencyAED
 
instance Hs.Ord Currency where
        compare x y
          = Hs.compare (HsProtobuf.fromProtoEnum x)
              (HsProtobuf.fromProtoEnum y)
 
instance HsProtobuf.ProtoEnum Currency where
        toProtoEnumMay 0 = Hs.Just CurrencyNO_CURRENCY
        toProtoEnumMay 1 = Hs.Just CurrencyINR
        toProtoEnumMay 2 = Hs.Just CurrencyUSD
        toProtoEnumMay 3 = Hs.Just CurrencyGBP
        toProtoEnumMay 4 = Hs.Just CurrencyEUR
        toProtoEnumMay 5 = Hs.Just CurrencyAED
        toProtoEnumMay _ = Hs.Nothing
        fromProtoEnum (CurrencyNO_CURRENCY) = 0
        fromProtoEnum (CurrencyINR) = 1
        fromProtoEnum (CurrencyUSD) = 2
        fromProtoEnum (CurrencyGBP) = 3
        fromProtoEnum (CurrencyEUR) = 4
        fromProtoEnum (CurrencyAED) = 5
 
instance HsJSONPB.ToJSONPB Currency where
        toJSONPB x _ = HsJSONPB.enumFieldString x
        toEncodingPB x _ = HsJSONPB.enumFieldEncoding x
 
instance HsJSONPB.FromJSONPB Currency where
        parseJSONPB (HsJSONPB.String "NO_CURRENCY")
          = Hs.pure CurrencyNO_CURRENCY
        parseJSONPB (HsJSONPB.String "INR") = Hs.pure CurrencyINR
        parseJSONPB (HsJSONPB.String "USD") = Hs.pure CurrencyUSD
        parseJSONPB (HsJSONPB.String "GBP") = Hs.pure CurrencyGBP
        parseJSONPB (HsJSONPB.String "EUR") = Hs.pure CurrencyEUR
        parseJSONPB (HsJSONPB.String "AED") = Hs.pure CurrencyAED
        parseJSONPB v = (HsJSONPB.typeMismatch "Currency" v)
 
instance HsJSONPB.ToJSON Currency where
        toJSON = HsJSONPB.toAesonValue
        toEncoding = HsJSONPB.toAesonEncoding
 
instance HsJSONPB.FromJSON Currency where
        parseJSON = HsJSONPB.parseJSONPB
 
instance HsProtobuf.Finite Currency
 
data OrderType = OrderTypeNO_ORDER_TYPE
               | OrderTypeMANDATE_REGISTER
               | OrderTypeMANDATE_PAYMENT
               | OrderTypeORDER_PAYMENT
               deriving (Hs.Show, Hs.Eq, Hs.Generic, Hs.NFData)
 
instance HsProtobuf.Named OrderType where
        nameOf _ = (Hs.fromString "OrderType")
 
instance HsProtobuf.HasDefault OrderType
 
instance Hs.Bounded OrderType where
        minBound = OrderTypeNO_ORDER_TYPE
        maxBound = OrderTypeORDER_PAYMENT
 
instance Hs.Ord OrderType where
        compare x y
          = Hs.compare (HsProtobuf.fromProtoEnum x)
              (HsProtobuf.fromProtoEnum y)
 
instance HsProtobuf.ProtoEnum OrderType where
        toProtoEnumMay 0 = Hs.Just OrderTypeNO_ORDER_TYPE
        toProtoEnumMay 1 = Hs.Just OrderTypeMANDATE_REGISTER
        toProtoEnumMay 2 = Hs.Just OrderTypeMANDATE_PAYMENT
        toProtoEnumMay 3 = Hs.Just OrderTypeORDER_PAYMENT
        toProtoEnumMay _ = Hs.Nothing
        fromProtoEnum (OrderTypeNO_ORDER_TYPE) = 0
        fromProtoEnum (OrderTypeMANDATE_REGISTER) = 1
        fromProtoEnum (OrderTypeMANDATE_PAYMENT) = 2
        fromProtoEnum (OrderTypeORDER_PAYMENT) = 3
 
instance HsJSONPB.ToJSONPB OrderType where
        toJSONPB x _ = HsJSONPB.enumFieldString x
        toEncodingPB x _ = HsJSONPB.enumFieldEncoding x
 
instance HsJSONPB.FromJSONPB OrderType where
        parseJSONPB (HsJSONPB.String "NO_ORDER_TYPE")
          = Hs.pure OrderTypeNO_ORDER_TYPE
        parseJSONPB (HsJSONPB.String "MANDATE_REGISTER")
          = Hs.pure OrderTypeMANDATE_REGISTER
        parseJSONPB (HsJSONPB.String "MANDATE_PAYMENT")
          = Hs.pure OrderTypeMANDATE_PAYMENT
        parseJSONPB (HsJSONPB.String "ORDER_PAYMENT")
          = Hs.pure OrderTypeORDER_PAYMENT
        parseJSONPB v = (HsJSONPB.typeMismatch "OrderType" v)
 
instance HsJSONPB.ToJSON OrderType where
        toJSON = HsJSONPB.toAesonValue
        toEncoding = HsJSONPB.toAesonEncoding
 
instance HsJSONPB.FromJSON OrderType where
        parseJSON = HsJSONPB.parseJSONPB
 
instance HsProtobuf.Finite OrderType
 
data OrderStatus = OrderStatusNO_ORDER_STATUS
                 | OrderStatusORDER_STATUS_NEW
                 | OrderStatusORDER_STATUS_SUCCESS
                 | OrderStatusORDER_STATUS_NOT_FOUND
                 | OrderStatusORDER_STATUS_ERROR
                 | OrderStatusORDER_STATUS_JUSPAY_DECLINED
                 | OrderStatusORDER_STATUS_PENDING_AUTHENTICATION
                 | OrderStatusORDER_STATUS_AUTHENTICATION_FAILED
                 | OrderStatusORDER_STATUS_AUTHORIZATION_FAILED
                 | OrderStatusORDER_STATUS_AUTHORIZING
                 | OrderStatusORDER_STATUS_AUTHORIZED
                 | OrderStatusORDER_STATUS_CREATED
                 | OrderStatusORDER_STATUS_COD_INITIATED
                 | OrderStatusORDER_STATUS_VOIDED
                 | OrderStatusORDER_STATUS_VOID_INITIATED
                 | OrderStatusORDER_STATUS_CAPTURE_INITIATED
                 | OrderStatusORDER_STATUS_CAPTURE_FAILED
                 | OrderStatusORDER_STATUS_VOID_FAILED
                 | OrderStatusORDER_STATUS_AUTO_REFUNDED
                 deriving (Hs.Show, Hs.Eq, Hs.Generic, Hs.NFData)
 
instance HsProtobuf.Named OrderStatus where
        nameOf _ = (Hs.fromString "OrderStatus")
 
instance HsProtobuf.HasDefault OrderStatus
 
instance Hs.Bounded OrderStatus where
        minBound = OrderStatusNO_ORDER_STATUS
        maxBound = OrderStatusORDER_STATUS_AUTO_REFUNDED
 
instance Hs.Ord OrderStatus where
        compare x y
          = Hs.compare (HsProtobuf.fromProtoEnum x)
              (HsProtobuf.fromProtoEnum y)
 
instance HsProtobuf.ProtoEnum OrderStatus where
        toProtoEnumMay 0 = Hs.Just OrderStatusNO_ORDER_STATUS
        toProtoEnumMay 1 = Hs.Just OrderStatusORDER_STATUS_NEW
        toProtoEnumMay 2 = Hs.Just OrderStatusORDER_STATUS_SUCCESS
        toProtoEnumMay 3 = Hs.Just OrderStatusORDER_STATUS_NOT_FOUND
        toProtoEnumMay 4 = Hs.Just OrderStatusORDER_STATUS_ERROR
        toProtoEnumMay 5 = Hs.Just OrderStatusORDER_STATUS_JUSPAY_DECLINED
        toProtoEnumMay 6
          = Hs.Just OrderStatusORDER_STATUS_PENDING_AUTHENTICATION
        toProtoEnumMay 7
          = Hs.Just OrderStatusORDER_STATUS_AUTHENTICATION_FAILED
        toProtoEnumMay 8
          = Hs.Just OrderStatusORDER_STATUS_AUTHORIZATION_FAILED
        toProtoEnumMay 9 = Hs.Just OrderStatusORDER_STATUS_AUTHORIZING
        toProtoEnumMay 10 = Hs.Just OrderStatusORDER_STATUS_AUTHORIZED
        toProtoEnumMay 11 = Hs.Just OrderStatusORDER_STATUS_CREATED
        toProtoEnumMay 12 = Hs.Just OrderStatusORDER_STATUS_COD_INITIATED
        toProtoEnumMay 13 = Hs.Just OrderStatusORDER_STATUS_VOIDED
        toProtoEnumMay 14 = Hs.Just OrderStatusORDER_STATUS_VOID_INITIATED
        toProtoEnumMay 15
          = Hs.Just OrderStatusORDER_STATUS_CAPTURE_INITIATED
        toProtoEnumMay 16 = Hs.Just OrderStatusORDER_STATUS_CAPTURE_FAILED
        toProtoEnumMay 17 = Hs.Just OrderStatusORDER_STATUS_VOID_FAILED
        toProtoEnumMay 18 = Hs.Just OrderStatusORDER_STATUS_AUTO_REFUNDED
        toProtoEnumMay _ = Hs.Nothing
        fromProtoEnum (OrderStatusNO_ORDER_STATUS) = 0
        fromProtoEnum (OrderStatusORDER_STATUS_NEW) = 1
        fromProtoEnum (OrderStatusORDER_STATUS_SUCCESS) = 2
        fromProtoEnum (OrderStatusORDER_STATUS_NOT_FOUND) = 3
        fromProtoEnum (OrderStatusORDER_STATUS_ERROR) = 4
        fromProtoEnum (OrderStatusORDER_STATUS_JUSPAY_DECLINED) = 5
        fromProtoEnum (OrderStatusORDER_STATUS_PENDING_AUTHENTICATION) = 6
        fromProtoEnum (OrderStatusORDER_STATUS_AUTHENTICATION_FAILED) = 7
        fromProtoEnum (OrderStatusORDER_STATUS_AUTHORIZATION_FAILED) = 8
        fromProtoEnum (OrderStatusORDER_STATUS_AUTHORIZING) = 9
        fromProtoEnum (OrderStatusORDER_STATUS_AUTHORIZED) = 10
        fromProtoEnum (OrderStatusORDER_STATUS_CREATED) = 11
        fromProtoEnum (OrderStatusORDER_STATUS_COD_INITIATED) = 12
        fromProtoEnum (OrderStatusORDER_STATUS_VOIDED) = 13
        fromProtoEnum (OrderStatusORDER_STATUS_VOID_INITIATED) = 14
        fromProtoEnum (OrderStatusORDER_STATUS_CAPTURE_INITIATED) = 15
        fromProtoEnum (OrderStatusORDER_STATUS_CAPTURE_FAILED) = 16
        fromProtoEnum (OrderStatusORDER_STATUS_VOID_FAILED) = 17
        fromProtoEnum (OrderStatusORDER_STATUS_AUTO_REFUNDED) = 18
 
instance HsJSONPB.ToJSONPB OrderStatus where
        toJSONPB x _ = HsJSONPB.enumFieldString x
        toEncodingPB x _ = HsJSONPB.enumFieldEncoding x
 
instance HsJSONPB.FromJSONPB OrderStatus where
        parseJSONPB (HsJSONPB.String "NO_ORDER_STATUS")
          = Hs.pure OrderStatusNO_ORDER_STATUS
        parseJSONPB (HsJSONPB.String "ORDER_STATUS_NEW")
          = Hs.pure OrderStatusORDER_STATUS_NEW
        parseJSONPB (HsJSONPB.String "ORDER_STATUS_SUCCESS")
          = Hs.pure OrderStatusORDER_STATUS_SUCCESS
        parseJSONPB (HsJSONPB.String "ORDER_STATUS_NOT_FOUND")
          = Hs.pure OrderStatusORDER_STATUS_NOT_FOUND
        parseJSONPB (HsJSONPB.String "ORDER_STATUS_ERROR")
          = Hs.pure OrderStatusORDER_STATUS_ERROR
        parseJSONPB (HsJSONPB.String "ORDER_STATUS_JUSPAY_DECLINED")
          = Hs.pure OrderStatusORDER_STATUS_JUSPAY_DECLINED
        parseJSONPB (HsJSONPB.String "ORDER_STATUS_PENDING_AUTHENTICATION")
          = Hs.pure OrderStatusORDER_STATUS_PENDING_AUTHENTICATION
        parseJSONPB (HsJSONPB.String "ORDER_STATUS_AUTHENTICATION_FAILED")
          = Hs.pure OrderStatusORDER_STATUS_AUTHENTICATION_FAILED
        parseJSONPB (HsJSONPB.String "ORDER_STATUS_AUTHORIZATION_FAILED")
          = Hs.pure OrderStatusORDER_STATUS_AUTHORIZATION_FAILED
        parseJSONPB (HsJSONPB.String "ORDER_STATUS_AUTHORIZING")
          = Hs.pure OrderStatusORDER_STATUS_AUTHORIZING
        parseJSONPB (HsJSONPB.String "ORDER_STATUS_AUTHORIZED")
          = Hs.pure OrderStatusORDER_STATUS_AUTHORIZED
        parseJSONPB (HsJSONPB.String "ORDER_STATUS_CREATED")
          = Hs.pure OrderStatusORDER_STATUS_CREATED
        parseJSONPB (HsJSONPB.String "ORDER_STATUS_COD_INITIATED")
          = Hs.pure OrderStatusORDER_STATUS_COD_INITIATED
        parseJSONPB (HsJSONPB.String "ORDER_STATUS_VOIDED")
          = Hs.pure OrderStatusORDER_STATUS_VOIDED
        parseJSONPB (HsJSONPB.String "ORDER_STATUS_VOID_INITIATED")
          = Hs.pure OrderStatusORDER_STATUS_VOID_INITIATED
        parseJSONPB (HsJSONPB.String "ORDER_STATUS_CAPTURE_INITIATED")
          = Hs.pure OrderStatusORDER_STATUS_CAPTURE_INITIATED
        parseJSONPB (HsJSONPB.String "ORDER_STATUS_CAPTURE_FAILED")
          = Hs.pure OrderStatusORDER_STATUS_CAPTURE_FAILED
        parseJSONPB (HsJSONPB.String "ORDER_STATUS_VOID_FAILED")
          = Hs.pure OrderStatusORDER_STATUS_VOID_FAILED
        parseJSONPB (HsJSONPB.String "ORDER_STATUS_AUTO_REFUNDED")
          = Hs.pure OrderStatusORDER_STATUS_AUTO_REFUNDED
        parseJSONPB v = (HsJSONPB.typeMismatch "OrderStatus" v)
 
instance HsJSONPB.ToJSON OrderStatus where
        toJSON = HsJSONPB.toAesonValue
        toEncoding = HsJSONPB.toAesonEncoding
 
instance HsJSONPB.FromJSON OrderStatus where
        parseJSON = HsJSONPB.parseJSONPB
 
instance HsProtobuf.Finite OrderStatus
 
data UDF = UDF{udfUdf1 :: Hs.Text, udfUdf2 :: Hs.Text,
               udfUdf3 :: Hs.Text, udfUdf4 :: Hs.Text, udfUdf5 :: Hs.Text,
               udfUdf6 :: Hs.Text, udfUdf7 :: Hs.Text, udfUdf8 :: Hs.Text,
               udfUdf9 :: Hs.Text, udfUdf10 :: Hs.Text}
         deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic, Hs.NFData)
 
instance HsProtobuf.Named UDF where
        nameOf _ = (Hs.fromString "UDF")
 
instance HsProtobuf.HasDefault UDF
 
instance HsProtobuf.Message UDF where
        encodeMessage _
          UDF{udfUdf1 = udfUdf1, udfUdf2 = udfUdf2, udfUdf3 = udfUdf3,
              udfUdf4 = udfUdf4, udfUdf5 = udfUdf5, udfUdf6 = udfUdf6,
              udfUdf7 = udfUdf7, udfUdf8 = udfUdf8, udfUdf9 = udfUdf9,
              udfUdf10 = udfUdf10}
          = (Hs.mconcat
               [(HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 1)
                   udfUdf1),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 2) udfUdf2),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 3) udfUdf3),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 4) udfUdf4),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 5) udfUdf5),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 6) udfUdf6),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 7) udfUdf7),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 8) udfUdf8),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 9) udfUdf9),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 10)
                   udfUdf10)])
        decodeMessage _
          = (Hs.pure UDF) <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 1))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 2))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 3))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 4))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 5))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 6))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 7))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 8))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 9))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 10))
        dotProto _
          = [(HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 1)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "udf1")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 2)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "udf2")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 3)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "udf3")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 4)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "udf4")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 5)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "udf5")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 6)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "udf6")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 7)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "udf7")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 8)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "udf8")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 9)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "udf9")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 10)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "udf10")
                []
                "")]
 
instance HsJSONPB.ToJSONPB UDF where
        toJSONPB (UDF f1 f2 f3 f4 f5 f6 f7 f8 f9 f10)
          = (HsJSONPB.object
               ["udf1" .= f1, "udf2" .= f2, "udf3" .= f3, "udf4" .= f4,
                "udf5" .= f5, "udf6" .= f6, "udf7" .= f7, "udf8" .= f8,
                "udf9" .= f9, "udf10" .= f10])
        toEncodingPB (UDF f1 f2 f3 f4 f5 f6 f7 f8 f9 f10)
          = (HsJSONPB.pairs
               ["udf1" .= f1, "udf2" .= f2, "udf3" .= f3, "udf4" .= f4,
                "udf5" .= f5, "udf6" .= f6, "udf7" .= f7, "udf8" .= f8,
                "udf9" .= f9, "udf10" .= f10])
 
instance HsJSONPB.FromJSONPB UDF where
        parseJSONPB
          = (HsJSONPB.withObject "UDF"
               (\ obj ->
                  (Hs.pure UDF) <*> obj .: "udf1" <*> obj .: "udf2" <*> obj .: "udf3"
                    <*> obj .: "udf4"
                    <*> obj .: "udf5"
                    <*> obj .: "udf6"
                    <*> obj .: "udf7"
                    <*> obj .: "udf8"
                    <*> obj .: "udf9"
                    <*> obj .: "udf10"))
 
instance HsJSONPB.ToJSON UDF where
        toJSON = HsJSONPB.toAesonValue
        toEncoding = HsJSONPB.toAesonEncoding
 
instance HsJSONPB.FromJSON UDF where
        parseJSON = HsJSONPB.parseJSONPB
 
instance HsJSONPB.ToSchema UDF where
        declareNamedSchema _
          = do let declare_udf1 = HsJSONPB.declareSchemaRef
               udfUdf1 <- declare_udf1 Proxy.Proxy
               let declare_udf2 = HsJSONPB.declareSchemaRef
               udfUdf2 <- declare_udf2 Proxy.Proxy
               let declare_udf3 = HsJSONPB.declareSchemaRef
               udfUdf3 <- declare_udf3 Proxy.Proxy
               let declare_udf4 = HsJSONPB.declareSchemaRef
               udfUdf4 <- declare_udf4 Proxy.Proxy
               let declare_udf5 = HsJSONPB.declareSchemaRef
               udfUdf5 <- declare_udf5 Proxy.Proxy
               let declare_udf6 = HsJSONPB.declareSchemaRef
               udfUdf6 <- declare_udf6 Proxy.Proxy
               let declare_udf7 = HsJSONPB.declareSchemaRef
               udfUdf7 <- declare_udf7 Proxy.Proxy
               let declare_udf8 = HsJSONPB.declareSchemaRef
               udfUdf8 <- declare_udf8 Proxy.Proxy
               let declare_udf9 = HsJSONPB.declareSchemaRef
               udfUdf9 <- declare_udf9 Proxy.Proxy
               let declare_udf10 = HsJSONPB.declareSchemaRef
               udfUdf10 <- declare_udf10 Proxy.Proxy
               let _ = Hs.pure UDF <*> HsJSONPB.asProxy declare_udf1 <*>
                         HsJSONPB.asProxy declare_udf2
                         <*> HsJSONPB.asProxy declare_udf3
                         <*> HsJSONPB.asProxy declare_udf4
                         <*> HsJSONPB.asProxy declare_udf5
                         <*> HsJSONPB.asProxy declare_udf6
                         <*> HsJSONPB.asProxy declare_udf7
                         <*> HsJSONPB.asProxy declare_udf8
                         <*> HsJSONPB.asProxy declare_udf9
                         <*> HsJSONPB.asProxy declare_udf10
               Hs.return
                 (HsJSONPB.NamedSchema{HsJSONPB._namedSchemaName = Hs.Just "UDF",
                                       HsJSONPB._namedSchemaSchema =
                                         Hs.mempty{HsJSONPB._schemaParamSchema =
                                                     Hs.mempty{HsJSONPB._paramSchemaType =
                                                                 Hs.Just HsJSONPB.SwaggerObject},
                                                   HsJSONPB._schemaProperties =
                                                     HsJSONPB.insOrdFromList
                                                       [("udf1", udfUdf1), ("udf2", udfUdf2),
                                                        ("udf3", udfUdf3), ("udf4", udfUdf4),
                                                        ("udf5", udfUdf5), ("udf6", udfUdf6),
                                                        ("udf7", udfUdf7), ("udf8", udfUdf8),
                                                        ("udf9", udfUdf9), ("udf10", udfUdf10)]}})
 
data MandateFeature = MandateFeatureNO_MANDATE_FEATURE
                    | MandateFeatureDISABLED
                    | MandateFeatureREQUIRED
                    | MandateFeatureOPTIONAL
                    deriving (Hs.Show, Hs.Eq, Hs.Generic, Hs.NFData)
 
instance HsProtobuf.Named MandateFeature where
        nameOf _ = (Hs.fromString "MandateFeature")
 
instance HsProtobuf.HasDefault MandateFeature
 
instance Hs.Bounded MandateFeature where
        minBound = MandateFeatureNO_MANDATE_FEATURE
        maxBound = MandateFeatureOPTIONAL
 
instance Hs.Ord MandateFeature where
        compare x y
          = Hs.compare (HsProtobuf.fromProtoEnum x)
              (HsProtobuf.fromProtoEnum y)
 
instance HsProtobuf.ProtoEnum MandateFeature where
        toProtoEnumMay 0 = Hs.Just MandateFeatureNO_MANDATE_FEATURE
        toProtoEnumMay 1 = Hs.Just MandateFeatureDISABLED
        toProtoEnumMay 2 = Hs.Just MandateFeatureREQUIRED
        toProtoEnumMay 3 = Hs.Just MandateFeatureOPTIONAL
        toProtoEnumMay _ = Hs.Nothing
        fromProtoEnum (MandateFeatureNO_MANDATE_FEATURE) = 0
        fromProtoEnum (MandateFeatureDISABLED) = 1
        fromProtoEnum (MandateFeatureREQUIRED) = 2
        fromProtoEnum (MandateFeatureOPTIONAL) = 3
 
instance HsJSONPB.ToJSONPB MandateFeature where
        toJSONPB x _ = HsJSONPB.enumFieldString x
        toEncodingPB x _ = HsJSONPB.enumFieldEncoding x
 
instance HsJSONPB.FromJSONPB MandateFeature where
        parseJSONPB (HsJSONPB.String "NO_MANDATE_FEATURE")
          = Hs.pure MandateFeatureNO_MANDATE_FEATURE
        parseJSONPB (HsJSONPB.String "DISABLED")
          = Hs.pure MandateFeatureDISABLED
        parseJSONPB (HsJSONPB.String "REQUIRED")
          = Hs.pure MandateFeatureREQUIRED
        parseJSONPB (HsJSONPB.String "OPTIONAL")
          = Hs.pure MandateFeatureOPTIONAL
        parseJSONPB v = (HsJSONPB.typeMismatch "MandateFeature" v)
 
instance HsJSONPB.ToJSON MandateFeature where
        toJSON = HsJSONPB.toAesonValue
        toEncoding = HsJSONPB.toAesonEncoding
 
instance HsJSONPB.FromJSON MandateFeature where
        parseJSON = HsJSONPB.parseJSONPB
 
instance HsProtobuf.Finite MandateFeature
 
data OrderEventType = OrderEventTypeNO_ORDER_EVENT_TYPE
                    | OrderEventTypeORDER_EVENT_CREATE
                    | OrderEventTypeORDER_EVENT_UPDATE
                    deriving (Hs.Show, Hs.Eq, Hs.Generic, Hs.NFData)
 
instance HsProtobuf.Named OrderEventType where
        nameOf _ = (Hs.fromString "OrderEventType")
 
instance HsProtobuf.HasDefault OrderEventType
 
instance Hs.Bounded OrderEventType where
        minBound = OrderEventTypeNO_ORDER_EVENT_TYPE
        maxBound = OrderEventTypeORDER_EVENT_UPDATE
 
instance Hs.Ord OrderEventType where
        compare x y
          = Hs.compare (HsProtobuf.fromProtoEnum x)
              (HsProtobuf.fromProtoEnum y)
 
instance HsProtobuf.ProtoEnum OrderEventType where
        toProtoEnumMay 0 = Hs.Just OrderEventTypeNO_ORDER_EVENT_TYPE
        toProtoEnumMay 1 = Hs.Just OrderEventTypeORDER_EVENT_CREATE
        toProtoEnumMay 2 = Hs.Just OrderEventTypeORDER_EVENT_UPDATE
        toProtoEnumMay _ = Hs.Nothing
        fromProtoEnum (OrderEventTypeNO_ORDER_EVENT_TYPE) = 0
        fromProtoEnum (OrderEventTypeORDER_EVENT_CREATE) = 1
        fromProtoEnum (OrderEventTypeORDER_EVENT_UPDATE) = 2
 
instance HsJSONPB.ToJSONPB OrderEventType where
        toJSONPB x _ = HsJSONPB.enumFieldString x
        toEncodingPB x _ = HsJSONPB.enumFieldEncoding x
 
instance HsJSONPB.FromJSONPB OrderEventType where
        parseJSONPB (HsJSONPB.String "NO_ORDER_EVENT_TYPE")
          = Hs.pure OrderEventTypeNO_ORDER_EVENT_TYPE
        parseJSONPB (HsJSONPB.String "ORDER_EVENT_CREATE")
          = Hs.pure OrderEventTypeORDER_EVENT_CREATE
        parseJSONPB (HsJSONPB.String "ORDER_EVENT_UPDATE")
          = Hs.pure OrderEventTypeORDER_EVENT_UPDATE
        parseJSONPB v = (HsJSONPB.typeMismatch "OrderEventType" v)
 
instance HsJSONPB.ToJSON OrderEventType where
        toJSON = HsJSONPB.toAesonValue
        toEncoding = HsJSONPB.toAesonEncoding
 
instance HsJSONPB.FromJSON OrderEventType where
        parseJSON = HsJSONPB.parseJSONPB
 
instance HsProtobuf.Finite OrderEventType