{-# LANGUAGE DeriveGeneric     #-}
{-# LANGUAGE DeriveAnyClass    #-}
{-# LANGUAGE DataKinds         #-}
{-# LANGUAGE GADTs             #-}
{-# LANGUAGE TypeApplications  #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing #-}
{-# OPTIONS_GHC -fno-warn-unused-matches #-}

-- | Generated by Haskell protocol buffer compiler. DO NOT EDIT!
module Euler.Proto.Event.Refund where
import qualified Prelude as Hs
import qualified Proto3.Suite.Class as HsProtobuf
import qualified Proto3.Suite.DotProto as HsProtobuf
import qualified Proto3.Suite.JSONPB as HsJSONPB
import Proto3.Suite.JSONPB ((.=), (.:))
import qualified Proto3.Suite.Types as HsProtobuf
import qualified Proto3.Wire as HsProtobuf
import qualified Control.Applicative as Hs
import Control.Applicative ((<*>), (<|>), (<$>))
import qualified Control.DeepSeq as Hs
import qualified Control.Monad as Hs
import qualified Data.ByteString as Hs
import qualified Data.Coerce as Hs
import qualified Data.Int as Hs (Int16, Int32, Int64)
import qualified Data.List.NonEmpty as Hs (NonEmpty(..))
import qualified Data.Map as Hs (Map, mapKeysMonotonic)
import qualified Data.Proxy as Proxy
import qualified Data.String as Hs (fromString)
import qualified Data.Text.Lazy as Hs (Text)
import qualified Data.Vector as Hs (Vector)
import qualified Data.Word as Hs (Word16, Word32, Word64)
import qualified GHC.Enum as Hs
import qualified GHC.Generics as Hs
import qualified Unsafe.Coerce as Hs
 
data Refund = Refund{refundId :: Hs.Int64,
                     refundAmount :: Hs.Double, refundAuthorizationId :: Hs.Text,
                     refundDateCreated :: Hs.Int64, refundEpgTxnId :: Hs.Text,
                     refundGateway :: Hs.Text, refundProcessed :: Hs.Bool,
                     refundRootReferenceNumber :: Hs.Text,
                     refundTxnDetailId :: Hs.Int64, refundReferenceId :: Hs.Text,
                     refundStatus ::
                     HsProtobuf.Enumerated Euler.Proto.Event.Refund.RefundStatus,
                     refundUniqueRequestId :: Hs.Text, refundErrorMessage :: Hs.Text,
                     refundSentToGateway :: Hs.Bool, refundResponseCode :: Hs.Text,
                     refundInternalReferenceId :: Hs.Text, refundRefundArn :: Hs.Text,
                     refundInitiatedBy :: Hs.Text, refundRefundType :: Hs.Text,
                     refundRefundSource :: Hs.Text, refundLastModified :: Hs.Int64,
                     refundRefundEventType ::
                     HsProtobuf.Enumerated Euler.Proto.Event.Refund.RefundEventType}
            deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic, Hs.NFData)
 
instance HsProtobuf.Named Refund where
        nameOf _ = (Hs.fromString "Refund")
 
instance HsProtobuf.HasDefault Refund
 
instance HsProtobuf.Message Refund where
        encodeMessage _
          Refund{refundId = refundId, refundAmount = refundAmount,
                 refundAuthorizationId = refundAuthorizationId,
                 refundDateCreated = refundDateCreated,
                 refundEpgTxnId = refundEpgTxnId, refundGateway = refundGateway,
                 refundProcessed = refundProcessed,
                 refundRootReferenceNumber = refundRootReferenceNumber,
                 refundTxnDetailId = refundTxnDetailId,
                 refundReferenceId = refundReferenceId, refundStatus = refundStatus,
                 refundUniqueRequestId = refundUniqueRequestId,
                 refundErrorMessage = refundErrorMessage,
                 refundSentToGateway = refundSentToGateway,
                 refundResponseCode = refundResponseCode,
                 refundInternalReferenceId = refundInternalReferenceId,
                 refundRefundArn = refundRefundArn,
                 refundInitiatedBy = refundInitiatedBy,
                 refundRefundType = refundRefundType,
                 refundRefundSource = refundRefundSource,
                 refundLastModified = refundLastModified,
                 refundRefundEventType = refundRefundEventType}
          = (Hs.mconcat
               [(HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 1)
                   refundId),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 2)
                   refundAmount),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 3)
                   refundAuthorizationId),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 4)
                   refundDateCreated),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 5)
                   refundEpgTxnId),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 6)
                   refundGateway),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 7)
                   refundProcessed),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 8)
                   refundRootReferenceNumber),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 9)
                   refundTxnDetailId),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 10)
                   refundReferenceId),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 11)
                   refundStatus),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 12)
                   refundUniqueRequestId),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 13)
                   refundErrorMessage),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 14)
                   refundSentToGateway),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 15)
                   refundResponseCode),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 16)
                   refundInternalReferenceId),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 17)
                   refundRefundArn),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 18)
                   refundInitiatedBy),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 19)
                   refundRefundType),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 20)
                   refundRefundSource),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 21)
                   refundLastModified),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 22)
                   refundRefundEventType)])
        decodeMessage _
          = (Hs.pure Refund) <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 1))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 2))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 3))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 4))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 5))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 6))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 7))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 8))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 9))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 10))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 11))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 12))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 13))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 14))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 15))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 16))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 17))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 18))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 19))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 20))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 21))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 22))
        dotProto _
          = [(HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 1)
                (HsProtobuf.Prim HsProtobuf.Int64)
                (HsProtobuf.Single "id")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 2)
                (HsProtobuf.Prim HsProtobuf.Double)
                (HsProtobuf.Single "amount")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 3)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "authorization_id")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 4)
                (HsProtobuf.Prim HsProtobuf.Int64)
                (HsProtobuf.Single "date_created")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 5)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "epg_txn_id")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 6)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "gateway")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 7)
                (HsProtobuf.Prim HsProtobuf.Bool)
                (HsProtobuf.Single "processed")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 8)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "root_reference_number")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 9)
                (HsProtobuf.Prim HsProtobuf.Int64)
                (HsProtobuf.Single "txn_detail_id")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 10)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "reference_id")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 11)
                (HsProtobuf.Prim
                   (HsProtobuf.Named (HsProtobuf.Single "RefundStatus")))
                (HsProtobuf.Single "status")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 12)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "unique_request_id")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 13)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "error_message")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 14)
                (HsProtobuf.Prim HsProtobuf.Bool)
                (HsProtobuf.Single "sent_to_gateway")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 15)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "response_code")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 16)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "internal_reference_id")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 17)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "refund_arn")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 18)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "initiated_by")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 19)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "refund_type")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 20)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "refund_source")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 21)
                (HsProtobuf.Prim HsProtobuf.Int64)
                (HsProtobuf.Single "last_modified")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 22)
                (HsProtobuf.Prim
                   (HsProtobuf.Named (HsProtobuf.Single "RefundEventType")))
                (HsProtobuf.Single "refund_event_type")
                []
                "")]
 
instance HsJSONPB.ToJSONPB Refund where
        toJSONPB
          (Refund f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14 f15 f16 f17
             f18 f19 f20 f21 f22)
          = (HsJSONPB.object
               ["id" .= f1, "amount" .= f2, "authorization_id" .= f3,
                "date_created" .= f4, "epg_txn_id" .= f5, "gateway" .= f6,
                "processed" .= f7, "root_reference_number" .= f8,
                "txn_detail_id" .= f9, "reference_id" .= f10, "status" .= f11,
                "unique_request_id" .= f12, "error_message" .= f13,
                "sent_to_gateway" .= f14, "response_code" .= f15,
                "internal_reference_id" .= f16, "refund_arn" .= f17,
                "initiated_by" .= f18, "refund_type" .= f19,
                "refund_source" .= f20, "last_modified" .= f21,
                "refund_event_type" .= f22])
        toEncodingPB
          (Refund f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14 f15 f16 f17
             f18 f19 f20 f21 f22)
          = (HsJSONPB.pairs
               ["id" .= f1, "amount" .= f2, "authorization_id" .= f3,
                "date_created" .= f4, "epg_txn_id" .= f5, "gateway" .= f6,
                "processed" .= f7, "root_reference_number" .= f8,
                "txn_detail_id" .= f9, "reference_id" .= f10, "status" .= f11,
                "unique_request_id" .= f12, "error_message" .= f13,
                "sent_to_gateway" .= f14, "response_code" .= f15,
                "internal_reference_id" .= f16, "refund_arn" .= f17,
                "initiated_by" .= f18, "refund_type" .= f19,
                "refund_source" .= f20, "last_modified" .= f21,
                "refund_event_type" .= f22])
 
instance HsJSONPB.FromJSONPB Refund where
        parseJSONPB
          = (HsJSONPB.withObject "Refund"
               (\ obj ->
                  (Hs.pure Refund) <*> obj .: "id" <*> obj .: "amount" <*>
                    obj .: "authorization_id"
                    <*> obj .: "date_created"
                    <*> obj .: "epg_txn_id"
                    <*> obj .: "gateway"
                    <*> obj .: "processed"
                    <*> obj .: "root_reference_number"
                    <*> obj .: "txn_detail_id"
                    <*> obj .: "reference_id"
                    <*> obj .: "status"
                    <*> obj .: "unique_request_id"
                    <*> obj .: "error_message"
                    <*> obj .: "sent_to_gateway"
                    <*> obj .: "response_code"
                    <*> obj .: "internal_reference_id"
                    <*> obj .: "refund_arn"
                    <*> obj .: "initiated_by"
                    <*> obj .: "refund_type"
                    <*> obj .: "refund_source"
                    <*> obj .: "last_modified"
                    <*> obj .: "refund_event_type"))
 
instance HsJSONPB.ToJSON Refund where
        toJSON = HsJSONPB.toAesonValue
        toEncoding = HsJSONPB.toAesonEncoding
 
instance HsJSONPB.FromJSON Refund where
        parseJSON = HsJSONPB.parseJSONPB
 
instance HsJSONPB.ToSchema Refund where
        declareNamedSchema _
          = do let declare_id = HsJSONPB.declareSchemaRef
               refundId <- declare_id Proxy.Proxy
               let declare_amount = HsJSONPB.declareSchemaRef
               refundAmount <- declare_amount Proxy.Proxy
               let declare_authorization_id = HsJSONPB.declareSchemaRef
               refundAuthorizationId <- declare_authorization_id Proxy.Proxy
               let declare_date_created = HsJSONPB.declareSchemaRef
               refundDateCreated <- declare_date_created Proxy.Proxy
               let declare_epg_txn_id = HsJSONPB.declareSchemaRef
               refundEpgTxnId <- declare_epg_txn_id Proxy.Proxy
               let declare_gateway = HsJSONPB.declareSchemaRef
               refundGateway <- declare_gateway Proxy.Proxy
               let declare_processed = HsJSONPB.declareSchemaRef
               refundProcessed <- declare_processed Proxy.Proxy
               let declare_root_reference_number = HsJSONPB.declareSchemaRef
               refundRootReferenceNumber <- declare_root_reference_number
                                              Proxy.Proxy
               let declare_txn_detail_id = HsJSONPB.declareSchemaRef
               refundTxnDetailId <- declare_txn_detail_id Proxy.Proxy
               let declare_reference_id = HsJSONPB.declareSchemaRef
               refundReferenceId <- declare_reference_id Proxy.Proxy
               let declare_status = HsJSONPB.declareSchemaRef
               refundStatus <- declare_status Proxy.Proxy
               let declare_unique_request_id = HsJSONPB.declareSchemaRef
               refundUniqueRequestId <- declare_unique_request_id Proxy.Proxy
               let declare_error_message = HsJSONPB.declareSchemaRef
               refundErrorMessage <- declare_error_message Proxy.Proxy
               let declare_sent_to_gateway = HsJSONPB.declareSchemaRef
               refundSentToGateway <- declare_sent_to_gateway Proxy.Proxy
               let declare_response_code = HsJSONPB.declareSchemaRef
               refundResponseCode <- declare_response_code Proxy.Proxy
               let declare_internal_reference_id = HsJSONPB.declareSchemaRef
               refundInternalReferenceId <- declare_internal_reference_id
                                              Proxy.Proxy
               let declare_refund_arn = HsJSONPB.declareSchemaRef
               refundRefundArn <- declare_refund_arn Proxy.Proxy
               let declare_initiated_by = HsJSONPB.declareSchemaRef
               refundInitiatedBy <- declare_initiated_by Proxy.Proxy
               let declare_refund_type = HsJSONPB.declareSchemaRef
               refundRefundType <- declare_refund_type Proxy.Proxy
               let declare_refund_source = HsJSONPB.declareSchemaRef
               refundRefundSource <- declare_refund_source Proxy.Proxy
               let declare_last_modified = HsJSONPB.declareSchemaRef
               refundLastModified <- declare_last_modified Proxy.Proxy
               let declare_refund_event_type = HsJSONPB.declareSchemaRef
               refundRefundEventType <- declare_refund_event_type Proxy.Proxy
               let _ = Hs.pure Refund <*> HsJSONPB.asProxy declare_id <*>
                         HsJSONPB.asProxy declare_amount
                         <*> HsJSONPB.asProxy declare_authorization_id
                         <*> HsJSONPB.asProxy declare_date_created
                         <*> HsJSONPB.asProxy declare_epg_txn_id
                         <*> HsJSONPB.asProxy declare_gateway
                         <*> HsJSONPB.asProxy declare_processed
                         <*> HsJSONPB.asProxy declare_root_reference_number
                         <*> HsJSONPB.asProxy declare_txn_detail_id
                         <*> HsJSONPB.asProxy declare_reference_id
                         <*> HsJSONPB.asProxy declare_status
                         <*> HsJSONPB.asProxy declare_unique_request_id
                         <*> HsJSONPB.asProxy declare_error_message
                         <*> HsJSONPB.asProxy declare_sent_to_gateway
                         <*> HsJSONPB.asProxy declare_response_code
                         <*> HsJSONPB.asProxy declare_internal_reference_id
                         <*> HsJSONPB.asProxy declare_refund_arn
                         <*> HsJSONPB.asProxy declare_initiated_by
                         <*> HsJSONPB.asProxy declare_refund_type
                         <*> HsJSONPB.asProxy declare_refund_source
                         <*> HsJSONPB.asProxy declare_last_modified
                         <*> HsJSONPB.asProxy declare_refund_event_type
               Hs.return
                 (HsJSONPB.NamedSchema{HsJSONPB._namedSchemaName = Hs.Just "Refund",
                                       HsJSONPB._namedSchemaSchema =
                                         Hs.mempty{HsJSONPB._schemaParamSchema =
                                                     Hs.mempty{HsJSONPB._paramSchemaType =
                                                                 Hs.Just HsJSONPB.SwaggerObject},
                                                   HsJSONPB._schemaProperties =
                                                     HsJSONPB.insOrdFromList
                                                       [("id", refundId), ("amount", refundAmount),
                                                        ("authorization_id", refundAuthorizationId),
                                                        ("date_created", refundDateCreated),
                                                        ("epg_txn_id", refundEpgTxnId),
                                                        ("gateway", refundGateway),
                                                        ("processed", refundProcessed),
                                                        ("root_reference_number",
                                                         refundRootReferenceNumber),
                                                        ("txn_detail_id", refundTxnDetailId),
                                                        ("reference_id", refundReferenceId),
                                                        ("status", refundStatus),
                                                        ("unique_request_id",
                                                         refundUniqueRequestId),
                                                        ("error_message", refundErrorMessage),
                                                        ("sent_to_gateway", refundSentToGateway),
                                                        ("response_code", refundResponseCode),
                                                        ("internal_reference_id",
                                                         refundInternalReferenceId),
                                                        ("refund_arn", refundRefundArn),
                                                        ("initiated_by", refundInitiatedBy),
                                                        ("refund_type", refundRefundType),
                                                        ("refund_source", refundRefundSource),
                                                        ("last_modified", refundLastModified),
                                                        ("refund_event_type",
                                                         refundRefundEventType)]}})
 
data RefundStatus = RefundStatusNO_REFUND_STATUS
                  | RefundStatusFAILURE
                  | RefundStatusMANUAL_REVIEW
                  | RefundStatusPENDING
                  | RefundStatusSUCCESS
                  | RefundStatusTRANSACTION_FAILURE
                  deriving (Hs.Show, Hs.Eq, Hs.Generic, Hs.NFData)
 
instance HsProtobuf.Named RefundStatus where
        nameOf _ = (Hs.fromString "RefundStatus")
 
instance HsProtobuf.HasDefault RefundStatus
 
instance Hs.Bounded RefundStatus where
        minBound = RefundStatusNO_REFUND_STATUS
        maxBound = RefundStatusTRANSACTION_FAILURE
 
instance Hs.Ord RefundStatus where
        compare x y
          = Hs.compare (HsProtobuf.fromProtoEnum x)
              (HsProtobuf.fromProtoEnum y)
 
instance HsProtobuf.ProtoEnum RefundStatus where
        toProtoEnumMay 0 = Hs.Just RefundStatusNO_REFUND_STATUS
        toProtoEnumMay 1 = Hs.Just RefundStatusFAILURE
        toProtoEnumMay 2 = Hs.Just RefundStatusMANUAL_REVIEW
        toProtoEnumMay 3 = Hs.Just RefundStatusPENDING
        toProtoEnumMay 4 = Hs.Just RefundStatusSUCCESS
        toProtoEnumMay 5 = Hs.Just RefundStatusTRANSACTION_FAILURE
        toProtoEnumMay _ = Hs.Nothing
        fromProtoEnum (RefundStatusNO_REFUND_STATUS) = 0
        fromProtoEnum (RefundStatusFAILURE) = 1
        fromProtoEnum (RefundStatusMANUAL_REVIEW) = 2
        fromProtoEnum (RefundStatusPENDING) = 3
        fromProtoEnum (RefundStatusSUCCESS) = 4
        fromProtoEnum (RefundStatusTRANSACTION_FAILURE) = 5
 
instance HsJSONPB.ToJSONPB RefundStatus where
        toJSONPB x _ = HsJSONPB.enumFieldString x
        toEncodingPB x _ = HsJSONPB.enumFieldEncoding x
 
instance HsJSONPB.FromJSONPB RefundStatus where
        parseJSONPB (HsJSONPB.String "NO_REFUND_STATUS")
          = Hs.pure RefundStatusNO_REFUND_STATUS
        parseJSONPB (HsJSONPB.String "FAILURE")
          = Hs.pure RefundStatusFAILURE
        parseJSONPB (HsJSONPB.String "MANUAL_REVIEW")
          = Hs.pure RefundStatusMANUAL_REVIEW
        parseJSONPB (HsJSONPB.String "PENDING")
          = Hs.pure RefundStatusPENDING
        parseJSONPB (HsJSONPB.String "SUCCESS")
          = Hs.pure RefundStatusSUCCESS
        parseJSONPB (HsJSONPB.String "TRANSACTION_FAILURE")
          = Hs.pure RefundStatusTRANSACTION_FAILURE
        parseJSONPB v = (HsJSONPB.typeMismatch "RefundStatus" v)
 
instance HsJSONPB.ToJSON RefundStatus where
        toJSON = HsJSONPB.toAesonValue
        toEncoding = HsJSONPB.toAesonEncoding
 
instance HsJSONPB.FromJSON RefundStatus where
        parseJSON = HsJSONPB.parseJSONPB
 
instance HsProtobuf.Finite RefundStatus
 
data RefundEventType = RefundEventTypeNO_REFUND_EVENT_TYPE
                     | RefundEventTypeREFUND_EVENT_CREATE
                     | RefundEventTypeREFUND_EVENT_UPDATE
                     deriving (Hs.Show, Hs.Eq, Hs.Generic, Hs.NFData)
 
instance HsProtobuf.Named RefundEventType where
        nameOf _ = (Hs.fromString "RefundEventType")
 
instance HsProtobuf.HasDefault RefundEventType
 
instance Hs.Bounded RefundEventType where
        minBound = RefundEventTypeNO_REFUND_EVENT_TYPE
        maxBound = RefundEventTypeREFUND_EVENT_UPDATE
 
instance Hs.Ord RefundEventType where
        compare x y
          = Hs.compare (HsProtobuf.fromProtoEnum x)
              (HsProtobuf.fromProtoEnum y)
 
instance HsProtobuf.ProtoEnum RefundEventType where
        toProtoEnumMay 0 = Hs.Just RefundEventTypeNO_REFUND_EVENT_TYPE
        toProtoEnumMay 1 = Hs.Just RefundEventTypeREFUND_EVENT_CREATE
        toProtoEnumMay 2 = Hs.Just RefundEventTypeREFUND_EVENT_UPDATE
        toProtoEnumMay _ = Hs.Nothing
        fromProtoEnum (RefundEventTypeNO_REFUND_EVENT_TYPE) = 0
        fromProtoEnum (RefundEventTypeREFUND_EVENT_CREATE) = 1
        fromProtoEnum (RefundEventTypeREFUND_EVENT_UPDATE) = 2
 
instance HsJSONPB.ToJSONPB RefundEventType where
        toJSONPB x _ = HsJSONPB.enumFieldString x
        toEncodingPB x _ = HsJSONPB.enumFieldEncoding x
 
instance HsJSONPB.FromJSONPB RefundEventType where
        parseJSONPB (HsJSONPB.String "NO_REFUND_EVENT_TYPE")
          = Hs.pure RefundEventTypeNO_REFUND_EVENT_TYPE
        parseJSONPB (HsJSONPB.String "REFUND_EVENT_CREATE")
          = Hs.pure RefundEventTypeREFUND_EVENT_CREATE
        parseJSONPB (HsJSONPB.String "REFUND_EVENT_UPDATE")
          = Hs.pure RefundEventTypeREFUND_EVENT_UPDATE
        parseJSONPB v = (HsJSONPB.typeMismatch "RefundEventType" v)
 
instance HsJSONPB.ToJSON RefundEventType where
        toJSON = HsJSONPB.toAesonValue
        toEncoding = HsJSONPB.toAesonEncoding
 
instance HsJSONPB.FromJSON RefundEventType where
        parseJSON = HsJSONPB.parseJSONPB
 
instance HsProtobuf.Finite RefundEventType