{-# LANGUAGE DeriveGeneric     #-}
{-# LANGUAGE DeriveAnyClass    #-}
{-# LANGUAGE DataKinds         #-}
{-# LANGUAGE GADTs             #-}
{-# LANGUAGE TypeApplications  #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing #-}
{-# OPTIONS_GHC -fno-warn-unused-matches #-}

-- | Generated by Haskell protocol buffer compiler. DO NOT EDIT!
module Euler.Proto.Event.Txn where
import qualified Prelude as Hs
import qualified Proto3.Suite.Class as HsProtobuf
import qualified Proto3.Suite.DotProto as HsProtobuf
import qualified Proto3.Suite.JSONPB as HsJSONPB
import Proto3.Suite.JSONPB ((.=), (.:))
import qualified Proto3.Suite.Types as HsProtobuf
import qualified Proto3.Wire as HsProtobuf
import qualified Control.Applicative as Hs
import Control.Applicative ((<*>), (<|>), (<$>))
import qualified Control.DeepSeq as Hs
import qualified Control.Monad as Hs
import qualified Data.ByteString as Hs
import qualified Data.Coerce as Hs
import qualified Data.Int as Hs (Int16, Int32, Int64)
import qualified Data.List.NonEmpty as Hs (NonEmpty(..))
import qualified Data.Map as Hs (Map, mapKeysMonotonic)
import qualified Data.Proxy as Proxy
import qualified Data.String as Hs (fromString)
import qualified Data.Text.Lazy as Hs (Text)
import qualified Data.Vector as Hs (Vector)
import qualified Data.Word as Hs (Word16, Word32, Word64)
import qualified GHC.Enum as Hs
import qualified GHC.Generics as Hs
import qualified Unsafe.Coerce as Hs
 
data Txn = Txn{txnId :: Hs.Int64, txnVersion :: Hs.Int64,
               txnOrderId :: Hs.Text,
               txnTxnStatus ::
               HsProtobuf.Enumerated Euler.Proto.Event.Txn.TxnStatus,
               txnTxnId :: Hs.Text, txnTxnType :: Hs.Text,
               txnDateCreated :: Hs.Int64, txnLastModified :: Hs.Int64,
               txnSuccessResponseId :: Hs.Int64, txnTxnMode :: Hs.Text,
               txnAddToLocker :: Hs.Bool, txnMerchantId :: Hs.Text,
               txnGateway :: HsProtobuf.Enumerated Euler.Proto.Event.Txn.Gateway,
               txnExpressCheckout :: Hs.Bool, txnRedirect :: Hs.Bool,
               txnGatewayPayload :: Hs.Text, txnIsEmi :: Hs.Bool,
               txnEmiBank :: Hs.Text, txnEmiTenure :: Hs.Int64,
               txnUsername :: Hs.Text, txnTxnUuid :: Hs.Text,
               txnMerchantGatewayAccountId :: Hs.Int64, txnTxnAmount :: Hs.Double,
               txnTxnObjectType :: Hs.Text, txnSourceObject :: Hs.Text,
               txnSourceObjectId :: Hs.Text, txnCurrency :: Hs.Text,
               txnNetAmount :: Hs.Double, txnSurchargeAmount :: Hs.Double,
               txnTaxAmount :: Hs.Double, txnBankErrorCode :: Hs.Text,
               txnBankErrorMessage :: Hs.Text, txnErrorMessage :: Hs.Text,
               txnTxnEventType ::
               HsProtobuf.Enumerated Euler.Proto.Event.Txn.TxnEventType}
         deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic, Hs.NFData)
 
instance HsProtobuf.Named Txn where
        nameOf _ = (Hs.fromString "Txn")
 
instance HsProtobuf.HasDefault Txn
 
instance HsProtobuf.Message Txn where
        encodeMessage _
          Txn{txnId = txnId, txnVersion = txnVersion,
              txnOrderId = txnOrderId, txnTxnStatus = txnTxnStatus,
              txnTxnId = txnTxnId, txnTxnType = txnTxnType,
              txnDateCreated = txnDateCreated, txnLastModified = txnLastModified,
              txnSuccessResponseId = txnSuccessResponseId,
              txnTxnMode = txnTxnMode, txnAddToLocker = txnAddToLocker,
              txnMerchantId = txnMerchantId, txnGateway = txnGateway,
              txnExpressCheckout = txnExpressCheckout, txnRedirect = txnRedirect,
              txnGatewayPayload = txnGatewayPayload, txnIsEmi = txnIsEmi,
              txnEmiBank = txnEmiBank, txnEmiTenure = txnEmiTenure,
              txnUsername = txnUsername, txnTxnUuid = txnTxnUuid,
              txnMerchantGatewayAccountId = txnMerchantGatewayAccountId,
              txnTxnAmount = txnTxnAmount, txnTxnObjectType = txnTxnObjectType,
              txnSourceObject = txnSourceObject,
              txnSourceObjectId = txnSourceObjectId, txnCurrency = txnCurrency,
              txnNetAmount = txnNetAmount,
              txnSurchargeAmount = txnSurchargeAmount,
              txnTaxAmount = txnTaxAmount, txnBankErrorCode = txnBankErrorCode,
              txnBankErrorMessage = txnBankErrorMessage,
              txnErrorMessage = txnErrorMessage,
              txnTxnEventType = txnTxnEventType}
          = (Hs.mconcat
               [(HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 1) txnId),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 2)
                   txnVersion),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 3)
                   txnOrderId),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 4)
                   txnTxnStatus),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 5)
                   txnTxnId),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 6)
                   txnTxnType),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 7)
                   txnDateCreated),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 8)
                   txnLastModified),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 9)
                   txnSuccessResponseId),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 10)
                   txnTxnMode),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 11)
                   txnAddToLocker),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 12)
                   txnMerchantId),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 13)
                   txnGateway),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 14)
                   txnExpressCheckout),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 15)
                   txnRedirect),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 16)
                   txnGatewayPayload),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 17)
                   txnIsEmi),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 18)
                   txnEmiBank),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 19)
                   txnEmiTenure),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 20)
                   txnUsername),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 21)
                   txnTxnUuid),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 22)
                   txnMerchantGatewayAccountId),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 23)
                   txnTxnAmount),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 24)
                   txnTxnObjectType),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 25)
                   txnSourceObject),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 26)
                   txnSourceObjectId),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 27)
                   txnCurrency),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 28)
                   txnNetAmount),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 29)
                   txnSurchargeAmount),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 30)
                   txnTaxAmount),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 31)
                   txnBankErrorCode),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 32)
                   txnBankErrorMessage),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 33)
                   txnErrorMessage),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 34)
                   txnTxnEventType)])
        decodeMessage _
          = (Hs.pure Txn) <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 1))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 2))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 3))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 4))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 5))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 6))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 7))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 8))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 9))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 10))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 11))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 12))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 13))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 14))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 15))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 16))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 17))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 18))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 19))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 20))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 21))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 22))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 23))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 24))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 25))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 26))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 27))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 28))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 29))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 30))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 31))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 32))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 33))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 34))
        dotProto _
          = [(HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 1)
                (HsProtobuf.Prim HsProtobuf.Int64)
                (HsProtobuf.Single "id")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 2)
                (HsProtobuf.Prim HsProtobuf.Int64)
                (HsProtobuf.Single "version")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 3)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "order_id")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 4)
                (HsProtobuf.Prim
                   (HsProtobuf.Named (HsProtobuf.Single "TxnStatus")))
                (HsProtobuf.Single "txn_status")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 5)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "txn_id")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 6)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "txn_type")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 7)
                (HsProtobuf.Prim HsProtobuf.Int64)
                (HsProtobuf.Single "date_created")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 8)
                (HsProtobuf.Prim HsProtobuf.Int64)
                (HsProtobuf.Single "last_modified")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 9)
                (HsProtobuf.Prim HsProtobuf.Int64)
                (HsProtobuf.Single "success_response_id")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 10)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "txn_mode")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 11)
                (HsProtobuf.Prim HsProtobuf.Bool)
                (HsProtobuf.Single "add_to_locker")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 12)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "merchant_id")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 13)
                (HsProtobuf.Prim (HsProtobuf.Named (HsProtobuf.Single "Gateway")))
                (HsProtobuf.Single "gateway")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 14)
                (HsProtobuf.Prim HsProtobuf.Bool)
                (HsProtobuf.Single "expressCheckout")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 15)
                (HsProtobuf.Prim HsProtobuf.Bool)
                (HsProtobuf.Single "redirect")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 16)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "gateway_payload")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 17)
                (HsProtobuf.Prim HsProtobuf.Bool)
                (HsProtobuf.Single "is_emi")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 18)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "emi_bank")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 19)
                (HsProtobuf.Prim HsProtobuf.Int64)
                (HsProtobuf.Single "emi_tenure")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 20)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "username")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 21)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "txn_uuid")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 22)
                (HsProtobuf.Prim HsProtobuf.Int64)
                (HsProtobuf.Single "merchant_gateway_account_id")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 23)
                (HsProtobuf.Prim HsProtobuf.Double)
                (HsProtobuf.Single "txn_amount")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 24)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "txn_object_type")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 25)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "source_object")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 26)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "source_object_id")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 27)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "currency")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 28)
                (HsProtobuf.Prim HsProtobuf.Double)
                (HsProtobuf.Single "net_amount")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 29)
                (HsProtobuf.Prim HsProtobuf.Double)
                (HsProtobuf.Single "surcharge_amount")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 30)
                (HsProtobuf.Prim HsProtobuf.Double)
                (HsProtobuf.Single "tax_amount")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 31)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "bank_error_code")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 32)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "bank_error_message")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 33)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "error_message")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 34)
                (HsProtobuf.Prim
                   (HsProtobuf.Named (HsProtobuf.Single "TxnEventType")))
                (HsProtobuf.Single "txn_event_type")
                []
                "")]
 
instance HsJSONPB.ToJSONPB Txn where
        toJSONPB
          (Txn f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14 f15 f16 f17 f18
             f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32 f33 f34)
          = (HsJSONPB.object
               ["id" .= f1, "version" .= f2, "order_id" .= f3, "txn_status" .= f4,
                "txn_id" .= f5, "txn_type" .= f6, "date_created" .= f7,
                "last_modified" .= f8, "success_response_id" .= f9,
                "txn_mode" .= f10, "add_to_locker" .= f11, "merchant_id" .= f12,
                "gateway" .= f13, "expressCheckout" .= f14, "redirect" .= f15,
                "gateway_payload" .= f16, "is_emi" .= f17, "emi_bank" .= f18,
                "emi_tenure" .= f19, "username" .= f20, "txn_uuid" .= f21,
                "merchant_gateway_account_id" .= f22, "txn_amount" .= f23,
                "txn_object_type" .= f24, "source_object" .= f25,
                "source_object_id" .= f26, "currency" .= f27, "net_amount" .= f28,
                "surcharge_amount" .= f29, "tax_amount" .= f30,
                "bank_error_code" .= f31, "bank_error_message" .= f32,
                "error_message" .= f33, "txn_event_type" .= f34])
        toEncodingPB
          (Txn f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14 f15 f16 f17 f18
             f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32 f33 f34)
          = (HsJSONPB.pairs
               ["id" .= f1, "version" .= f2, "order_id" .= f3, "txn_status" .= f4,
                "txn_id" .= f5, "txn_type" .= f6, "date_created" .= f7,
                "last_modified" .= f8, "success_response_id" .= f9,
                "txn_mode" .= f10, "add_to_locker" .= f11, "merchant_id" .= f12,
                "gateway" .= f13, "expressCheckout" .= f14, "redirect" .= f15,
                "gateway_payload" .= f16, "is_emi" .= f17, "emi_bank" .= f18,
                "emi_tenure" .= f19, "username" .= f20, "txn_uuid" .= f21,
                "merchant_gateway_account_id" .= f22, "txn_amount" .= f23,
                "txn_object_type" .= f24, "source_object" .= f25,
                "source_object_id" .= f26, "currency" .= f27, "net_amount" .= f28,
                "surcharge_amount" .= f29, "tax_amount" .= f30,
                "bank_error_code" .= f31, "bank_error_message" .= f32,
                "error_message" .= f33, "txn_event_type" .= f34])
 
instance HsJSONPB.FromJSONPB Txn where
        parseJSONPB
          = (HsJSONPB.withObject "Txn"
               (\ obj ->
                  (Hs.pure Txn) <*> obj .: "id" <*> obj .: "version" <*>
                    obj .: "order_id"
                    <*> obj .: "txn_status"
                    <*> obj .: "txn_id"
                    <*> obj .: "txn_type"
                    <*> obj .: "date_created"
                    <*> obj .: "last_modified"
                    <*> obj .: "success_response_id"
                    <*> obj .: "txn_mode"
                    <*> obj .: "add_to_locker"
                    <*> obj .: "merchant_id"
                    <*> obj .: "gateway"
                    <*> obj .: "expressCheckout"
                    <*> obj .: "redirect"
                    <*> obj .: "gateway_payload"
                    <*> obj .: "is_emi"
                    <*> obj .: "emi_bank"
                    <*> obj .: "emi_tenure"
                    <*> obj .: "username"
                    <*> obj .: "txn_uuid"
                    <*> obj .: "merchant_gateway_account_id"
                    <*> obj .: "txn_amount"
                    <*> obj .: "txn_object_type"
                    <*> obj .: "source_object"
                    <*> obj .: "source_object_id"
                    <*> obj .: "currency"
                    <*> obj .: "net_amount"
                    <*> obj .: "surcharge_amount"
                    <*> obj .: "tax_amount"
                    <*> obj .: "bank_error_code"
                    <*> obj .: "bank_error_message"
                    <*> obj .: "error_message"
                    <*> obj .: "txn_event_type"))
 
instance HsJSONPB.ToJSON Txn where
        toJSON = HsJSONPB.toAesonValue
        toEncoding = HsJSONPB.toAesonEncoding
 
instance HsJSONPB.FromJSON Txn where
        parseJSON = HsJSONPB.parseJSONPB
 
instance HsJSONPB.ToSchema Txn where
        declareNamedSchema _
          = do let declare_id = HsJSONPB.declareSchemaRef
               txnId <- declare_id Proxy.Proxy
               let declare_version = HsJSONPB.declareSchemaRef
               txnVersion <- declare_version Proxy.Proxy
               let declare_order_id = HsJSONPB.declareSchemaRef
               txnOrderId <- declare_order_id Proxy.Proxy
               let declare_txn_status = HsJSONPB.declareSchemaRef
               txnTxnStatus <- declare_txn_status Proxy.Proxy
               let declare_txn_id = HsJSONPB.declareSchemaRef
               txnTxnId <- declare_txn_id Proxy.Proxy
               let declare_txn_type = HsJSONPB.declareSchemaRef
               txnTxnType <- declare_txn_type Proxy.Proxy
               let declare_date_created = HsJSONPB.declareSchemaRef
               txnDateCreated <- declare_date_created Proxy.Proxy
               let declare_last_modified = HsJSONPB.declareSchemaRef
               txnLastModified <- declare_last_modified Proxy.Proxy
               let declare_success_response_id = HsJSONPB.declareSchemaRef
               txnSuccessResponseId <- declare_success_response_id Proxy.Proxy
               let declare_txn_mode = HsJSONPB.declareSchemaRef
               txnTxnMode <- declare_txn_mode Proxy.Proxy
               let declare_add_to_locker = HsJSONPB.declareSchemaRef
               txnAddToLocker <- declare_add_to_locker Proxy.Proxy
               let declare_merchant_id = HsJSONPB.declareSchemaRef
               txnMerchantId <- declare_merchant_id Proxy.Proxy
               let declare_gateway = HsJSONPB.declareSchemaRef
               txnGateway <- declare_gateway Proxy.Proxy
               let declare_expressCheckout = HsJSONPB.declareSchemaRef
               txnExpressCheckout <- declare_expressCheckout Proxy.Proxy
               let declare_redirect = HsJSONPB.declareSchemaRef
               txnRedirect <- declare_redirect Proxy.Proxy
               let declare_gateway_payload = HsJSONPB.declareSchemaRef
               txnGatewayPayload <- declare_gateway_payload Proxy.Proxy
               let declare_is_emi = HsJSONPB.declareSchemaRef
               txnIsEmi <- declare_is_emi Proxy.Proxy
               let declare_emi_bank = HsJSONPB.declareSchemaRef
               txnEmiBank <- declare_emi_bank Proxy.Proxy
               let declare_emi_tenure = HsJSONPB.declareSchemaRef
               txnEmiTenure <- declare_emi_tenure Proxy.Proxy
               let declare_username = HsJSONPB.declareSchemaRef
               txnUsername <- declare_username Proxy.Proxy
               let declare_txn_uuid = HsJSONPB.declareSchemaRef
               txnTxnUuid <- declare_txn_uuid Proxy.Proxy
               let declare_merchant_gateway_account_id = HsJSONPB.declareSchemaRef
               txnMerchantGatewayAccountId <- declare_merchant_gateway_account_id
                                                Proxy.Proxy
               let declare_txn_amount = HsJSONPB.declareSchemaRef
               txnTxnAmount <- declare_txn_amount Proxy.Proxy
               let declare_txn_object_type = HsJSONPB.declareSchemaRef
               txnTxnObjectType <- declare_txn_object_type Proxy.Proxy
               let declare_source_object = HsJSONPB.declareSchemaRef
               txnSourceObject <- declare_source_object Proxy.Proxy
               let declare_source_object_id = HsJSONPB.declareSchemaRef
               txnSourceObjectId <- declare_source_object_id Proxy.Proxy
               let declare_currency = HsJSONPB.declareSchemaRef
               txnCurrency <- declare_currency Proxy.Proxy
               let declare_net_amount = HsJSONPB.declareSchemaRef
               txnNetAmount <- declare_net_amount Proxy.Proxy
               let declare_surcharge_amount = HsJSONPB.declareSchemaRef
               txnSurchargeAmount <- declare_surcharge_amount Proxy.Proxy
               let declare_tax_amount = HsJSONPB.declareSchemaRef
               txnTaxAmount <- declare_tax_amount Proxy.Proxy
               let declare_bank_error_code = HsJSONPB.declareSchemaRef
               txnBankErrorCode <- declare_bank_error_code Proxy.Proxy
               let declare_bank_error_message = HsJSONPB.declareSchemaRef
               txnBankErrorMessage <- declare_bank_error_message Proxy.Proxy
               let declare_error_message = HsJSONPB.declareSchemaRef
               txnErrorMessage <- declare_error_message Proxy.Proxy
               let declare_txn_event_type = HsJSONPB.declareSchemaRef
               txnTxnEventType <- declare_txn_event_type Proxy.Proxy
               let _ = Hs.pure Txn <*> HsJSONPB.asProxy declare_id <*>
                         HsJSONPB.asProxy declare_version
                         <*> HsJSONPB.asProxy declare_order_id
                         <*> HsJSONPB.asProxy declare_txn_status
                         <*> HsJSONPB.asProxy declare_txn_id
                         <*> HsJSONPB.asProxy declare_txn_type
                         <*> HsJSONPB.asProxy declare_date_created
                         <*> HsJSONPB.asProxy declare_last_modified
                         <*> HsJSONPB.asProxy declare_success_response_id
                         <*> HsJSONPB.asProxy declare_txn_mode
                         <*> HsJSONPB.asProxy declare_add_to_locker
                         <*> HsJSONPB.asProxy declare_merchant_id
                         <*> HsJSONPB.asProxy declare_gateway
                         <*> HsJSONPB.asProxy declare_expressCheckout
                         <*> HsJSONPB.asProxy declare_redirect
                         <*> HsJSONPB.asProxy declare_gateway_payload
                         <*> HsJSONPB.asProxy declare_is_emi
                         <*> HsJSONPB.asProxy declare_emi_bank
                         <*> HsJSONPB.asProxy declare_emi_tenure
                         <*> HsJSONPB.asProxy declare_username
                         <*> HsJSONPB.asProxy declare_txn_uuid
                         <*> HsJSONPB.asProxy declare_merchant_gateway_account_id
                         <*> HsJSONPB.asProxy declare_txn_amount
                         <*> HsJSONPB.asProxy declare_txn_object_type
                         <*> HsJSONPB.asProxy declare_source_object
                         <*> HsJSONPB.asProxy declare_source_object_id
                         <*> HsJSONPB.asProxy declare_currency
                         <*> HsJSONPB.asProxy declare_net_amount
                         <*> HsJSONPB.asProxy declare_surcharge_amount
                         <*> HsJSONPB.asProxy declare_tax_amount
                         <*> HsJSONPB.asProxy declare_bank_error_code
                         <*> HsJSONPB.asProxy declare_bank_error_message
                         <*> HsJSONPB.asProxy declare_error_message
                         <*> HsJSONPB.asProxy declare_txn_event_type
               Hs.return
                 (HsJSONPB.NamedSchema{HsJSONPB._namedSchemaName = Hs.Just "Txn",
                                       HsJSONPB._namedSchemaSchema =
                                         Hs.mempty{HsJSONPB._schemaParamSchema =
                                                     Hs.mempty{HsJSONPB._paramSchemaType =
                                                                 Hs.Just HsJSONPB.SwaggerObject},
                                                   HsJSONPB._schemaProperties =
                                                     HsJSONPB.insOrdFromList
                                                       [("id", txnId), ("version", txnVersion),
                                                        ("order_id", txnOrderId),
                                                        ("txn_status", txnTxnStatus),
                                                        ("txn_id", txnTxnId),
                                                        ("txn_type", txnTxnType),
                                                        ("date_created", txnDateCreated),
                                                        ("last_modified", txnLastModified),
                                                        ("success_response_id",
                                                         txnSuccessResponseId),
                                                        ("txn_mode", txnTxnMode),
                                                        ("add_to_locker", txnAddToLocker),
                                                        ("merchant_id", txnMerchantId),
                                                        ("gateway", txnGateway),
                                                        ("expressCheckout", txnExpressCheckout),
                                                        ("redirect", txnRedirect),
                                                        ("gateway_payload", txnGatewayPayload),
                                                        ("is_emi", txnIsEmi),
                                                        ("emi_bank", txnEmiBank),
                                                        ("emi_tenure", txnEmiTenure),
                                                        ("username", txnUsername),
                                                        ("txn_uuid", txnTxnUuid),
                                                        ("merchant_gateway_account_id",
                                                         txnMerchantGatewayAccountId),
                                                        ("txn_amount", txnTxnAmount),
                                                        ("txn_object_type", txnTxnObjectType),
                                                        ("source_object", txnSourceObject),
                                                        ("source_object_id", txnSourceObjectId),
                                                        ("currency", txnCurrency),
                                                        ("net_amount", txnNetAmount),
                                                        ("surcharge_amount", txnSurchargeAmount),
                                                        ("tax_amount", txnTaxAmount),
                                                        ("bank_error_code", txnBankErrorCode),
                                                        ("bank_error_message", txnBankErrorMessage),
                                                        ("error_message", txnErrorMessage),
                                                        ("txn_event_type", txnTxnEventType)]}})
 
data TxnStatus = TxnStatusNO_TXN_STATUS
               | TxnStatusSTARTED
               | TxnStatusAUTHENTICATION_FAILED
               | TxnStatusJUSPAY_DECLINED
               | TxnStatusPENDING_VBV
               | TxnStatusVBV_SUCCESSFUL
               | TxnStatusAUTHORIZED
               | TxnStatusAUTHORIZATION_FAILED
               | TxnStatusCHARGED
               | TxnStatusAUTHORIZING
               | TxnStatusCOD_INITIATED
               | TxnStatusVOIDED
               | TxnStatusVOID_INITIATED
               | TxnStatusNOP
               | TxnStatusCAPTURE_INITIATED
               | TxnStatusCAPTURE_FAILED
               | TxnStatusVOID_FAILED
               deriving (Hs.Show, Hs.Eq, Hs.Generic, Hs.NFData)
 
instance HsProtobuf.Named TxnStatus where
        nameOf _ = (Hs.fromString "TxnStatus")
 
instance HsProtobuf.HasDefault TxnStatus
 
instance Hs.Bounded TxnStatus where
        minBound = TxnStatusNO_TXN_STATUS
        maxBound = TxnStatusVOID_FAILED
 
instance Hs.Ord TxnStatus where
        compare x y
          = Hs.compare (HsProtobuf.fromProtoEnum x)
              (HsProtobuf.fromProtoEnum y)
 
instance HsProtobuf.ProtoEnum TxnStatus where
        toProtoEnumMay 0 = Hs.Just TxnStatusNO_TXN_STATUS
        toProtoEnumMay 1 = Hs.Just TxnStatusSTARTED
        toProtoEnumMay 2 = Hs.Just TxnStatusAUTHENTICATION_FAILED
        toProtoEnumMay 3 = Hs.Just TxnStatusJUSPAY_DECLINED
        toProtoEnumMay 4 = Hs.Just TxnStatusPENDING_VBV
        toProtoEnumMay 5 = Hs.Just TxnStatusVBV_SUCCESSFUL
        toProtoEnumMay 6 = Hs.Just TxnStatusAUTHORIZED
        toProtoEnumMay 7 = Hs.Just TxnStatusAUTHORIZATION_FAILED
        toProtoEnumMay 8 = Hs.Just TxnStatusCHARGED
        toProtoEnumMay 9 = Hs.Just TxnStatusAUTHORIZING
        toProtoEnumMay 10 = Hs.Just TxnStatusCOD_INITIATED
        toProtoEnumMay 11 = Hs.Just TxnStatusVOIDED
        toProtoEnumMay 12 = Hs.Just TxnStatusVOID_INITIATED
        toProtoEnumMay 13 = Hs.Just TxnStatusNOP
        toProtoEnumMay 14 = Hs.Just TxnStatusCAPTURE_INITIATED
        toProtoEnumMay 15 = Hs.Just TxnStatusCAPTURE_FAILED
        toProtoEnumMay 16 = Hs.Just TxnStatusVOID_FAILED
        toProtoEnumMay _ = Hs.Nothing
        fromProtoEnum (TxnStatusNO_TXN_STATUS) = 0
        fromProtoEnum (TxnStatusSTARTED) = 1
        fromProtoEnum (TxnStatusAUTHENTICATION_FAILED) = 2
        fromProtoEnum (TxnStatusJUSPAY_DECLINED) = 3
        fromProtoEnum (TxnStatusPENDING_VBV) = 4
        fromProtoEnum (TxnStatusVBV_SUCCESSFUL) = 5
        fromProtoEnum (TxnStatusAUTHORIZED) = 6
        fromProtoEnum (TxnStatusAUTHORIZATION_FAILED) = 7
        fromProtoEnum (TxnStatusCHARGED) = 8
        fromProtoEnum (TxnStatusAUTHORIZING) = 9
        fromProtoEnum (TxnStatusCOD_INITIATED) = 10
        fromProtoEnum (TxnStatusVOIDED) = 11
        fromProtoEnum (TxnStatusVOID_INITIATED) = 12
        fromProtoEnum (TxnStatusNOP) = 13
        fromProtoEnum (TxnStatusCAPTURE_INITIATED) = 14
        fromProtoEnum (TxnStatusCAPTURE_FAILED) = 15
        fromProtoEnum (TxnStatusVOID_FAILED) = 16
 
instance HsJSONPB.ToJSONPB TxnStatus where
        toJSONPB x _ = HsJSONPB.enumFieldString x
        toEncodingPB x _ = HsJSONPB.enumFieldEncoding x
 
instance HsJSONPB.FromJSONPB TxnStatus where
        parseJSONPB (HsJSONPB.String "NO_TXN_STATUS")
          = Hs.pure TxnStatusNO_TXN_STATUS
        parseJSONPB (HsJSONPB.String "STARTED") = Hs.pure TxnStatusSTARTED
        parseJSONPB (HsJSONPB.String "AUTHENTICATION_FAILED")
          = Hs.pure TxnStatusAUTHENTICATION_FAILED
        parseJSONPB (HsJSONPB.String "JUSPAY_DECLINED")
          = Hs.pure TxnStatusJUSPAY_DECLINED
        parseJSONPB (HsJSONPB.String "PENDING_VBV")
          = Hs.pure TxnStatusPENDING_VBV
        parseJSONPB (HsJSONPB.String "VBV_SUCCESSFUL")
          = Hs.pure TxnStatusVBV_SUCCESSFUL
        parseJSONPB (HsJSONPB.String "AUTHORIZED")
          = Hs.pure TxnStatusAUTHORIZED
        parseJSONPB (HsJSONPB.String "AUTHORIZATION_FAILED")
          = Hs.pure TxnStatusAUTHORIZATION_FAILED
        parseJSONPB (HsJSONPB.String "CHARGED") = Hs.pure TxnStatusCHARGED
        parseJSONPB (HsJSONPB.String "AUTHORIZING")
          = Hs.pure TxnStatusAUTHORIZING
        parseJSONPB (HsJSONPB.String "COD_INITIATED")
          = Hs.pure TxnStatusCOD_INITIATED
        parseJSONPB (HsJSONPB.String "VOIDED") = Hs.pure TxnStatusVOIDED
        parseJSONPB (HsJSONPB.String "VOID_INITIATED")
          = Hs.pure TxnStatusVOID_INITIATED
        parseJSONPB (HsJSONPB.String "NOP") = Hs.pure TxnStatusNOP
        parseJSONPB (HsJSONPB.String "CAPTURE_INITIATED")
          = Hs.pure TxnStatusCAPTURE_INITIATED
        parseJSONPB (HsJSONPB.String "CAPTURE_FAILED")
          = Hs.pure TxnStatusCAPTURE_FAILED
        parseJSONPB (HsJSONPB.String "VOID_FAILED")
          = Hs.pure TxnStatusVOID_FAILED
        parseJSONPB v = (HsJSONPB.typeMismatch "TxnStatus" v)
 
instance HsJSONPB.ToJSON TxnStatus where
        toJSON = HsJSONPB.toAesonValue
        toEncoding = HsJSONPB.toAesonEncoding
 
instance HsJSONPB.FromJSON TxnStatus where
        parseJSON = HsJSONPB.parseJSONPB
 
instance HsProtobuf.Finite TxnStatus
 
data Gateway = GatewayNO_GATEWAY
             | GatewayAXIS
             | GatewayHDFC
             | GatewayICICI
             | GatewayCITI
             | GatewayAMEX
             | GatewayCYBERSOURCE
             | GatewayIPG
             | GatewayMIGS
             | GatewayKOTAK
             | GatewayEBS
             | GatewayPAYU
             | GatewayCCAVENUE
             | GatewayCITRUS
             | GatewayATOM
             | GatewayCCAVENUE_V2
             | GatewayTPSL
             | GatewayPAYTM
             | GatewayPAYTM_V2
             | GatewayPAYPAL
             | GatewayHDFC_EBS_VAS
             | GatewayPAYLATER
             | GatewayRAZORPAY
             | GatewayFSS_ATM_PIN
             | GatewayEBS_V3
             | GatewayZAAKPAY
             | GatewayBILLDESK
             | GatewaySODEXO
             | GatewayBLAZEPAY
             | GatewayFSS_ATM_PIN_V2
             | GatewayMOBIKWIK
             | GatewayOLAMONEY
             | GatewayFREECHARGE
             | GatewayMPESA
             | GatewaySBIBUDDY
             | GatewayJIOMONEY
             | GatewayAIRTELMONEY
             | GatewayAMAZONPAY
             | GatewayPHONEPE
             | GatewaySTRIPE
             | GatewayDUMMY
             | GatewayHDFC_IVR
             | GatewayZESTMONEY
             | GatewayEPAYLATER
             | GatewayAXISNB
             | GatewayICICINB
             | GatewayTPSL_SI
             | GatewayAXIS_UPI
             | GatewayHDFC_UPI
             | GatewayINDUS_UPI
             | GatewayKOTAK_UPI
             | GatewaySBI_UPI
             | GatewayICICI_UPI
             | GatewayVIJAYA_UPI
             | GatewayHSBC_UPI
             | GatewayYESBANK_UPI
             | GatewayPAYTM_UPI
             | GatewayLINEPAY
             | GatewayOLAPOSTPAID
             | GatewaySIMPL
             | GatewayGOOGLEPAY
             | GatewayGOCASHFREE
             | GatewayPAYFORT
             | GatewayFSSPAY
             | GatewayCASH
             | GatewayMORPHEUS
             | GatewayFREECHARGE_V2
             | GatewayLAZYPAY
             | GatewayITZCASH
             | GatewayAXIS_BIZ
             | GatewayLOANTAP
             | GatewayDEFAULT
             deriving (Hs.Show, Hs.Eq, Hs.Generic, Hs.NFData)
 
instance HsProtobuf.Named Gateway where
        nameOf _ = (Hs.fromString "Gateway")
 
instance HsProtobuf.HasDefault Gateway
 
instance Hs.Bounded Gateway where
        minBound = GatewayNO_GATEWAY
        maxBound = GatewayDEFAULT
 
instance Hs.Ord Gateway where
        compare x y
          = Hs.compare (HsProtobuf.fromProtoEnum x)
              (HsProtobuf.fromProtoEnum y)
 
instance HsProtobuf.ProtoEnum Gateway where
        toProtoEnumMay 0 = Hs.Just GatewayNO_GATEWAY
        toProtoEnumMay 1 = Hs.Just GatewayAXIS
        toProtoEnumMay 2 = Hs.Just GatewayHDFC
        toProtoEnumMay 3 = Hs.Just GatewayICICI
        toProtoEnumMay 4 = Hs.Just GatewayCITI
        toProtoEnumMay 5 = Hs.Just GatewayAMEX
        toProtoEnumMay 6 = Hs.Just GatewayCYBERSOURCE
        toProtoEnumMay 7 = Hs.Just GatewayIPG
        toProtoEnumMay 8 = Hs.Just GatewayMIGS
        toProtoEnumMay 9 = Hs.Just GatewayKOTAK
        toProtoEnumMay 10 = Hs.Just GatewayEBS
        toProtoEnumMay 11 = Hs.Just GatewayPAYU
        toProtoEnumMay 12 = Hs.Just GatewayCCAVENUE
        toProtoEnumMay 13 = Hs.Just GatewayCITRUS
        toProtoEnumMay 14 = Hs.Just GatewayATOM
        toProtoEnumMay 15 = Hs.Just GatewayCCAVENUE_V2
        toProtoEnumMay 16 = Hs.Just GatewayTPSL
        toProtoEnumMay 17 = Hs.Just GatewayPAYTM
        toProtoEnumMay 18 = Hs.Just GatewayPAYTM_V2
        toProtoEnumMay 19 = Hs.Just GatewayPAYPAL
        toProtoEnumMay 20 = Hs.Just GatewayHDFC_EBS_VAS
        toProtoEnumMay 21 = Hs.Just GatewayPAYLATER
        toProtoEnumMay 22 = Hs.Just GatewayRAZORPAY
        toProtoEnumMay 23 = Hs.Just GatewayFSS_ATM_PIN
        toProtoEnumMay 24 = Hs.Just GatewayEBS_V3
        toProtoEnumMay 25 = Hs.Just GatewayZAAKPAY
        toProtoEnumMay 26 = Hs.Just GatewayBILLDESK
        toProtoEnumMay 27 = Hs.Just GatewaySODEXO
        toProtoEnumMay 28 = Hs.Just GatewayBLAZEPAY
        toProtoEnumMay 29 = Hs.Just GatewayFSS_ATM_PIN_V2
        toProtoEnumMay 30 = Hs.Just GatewayMOBIKWIK
        toProtoEnumMay 31 = Hs.Just GatewayOLAMONEY
        toProtoEnumMay 32 = Hs.Just GatewayFREECHARGE
        toProtoEnumMay 33 = Hs.Just GatewayMPESA
        toProtoEnumMay 34 = Hs.Just GatewaySBIBUDDY
        toProtoEnumMay 35 = Hs.Just GatewayJIOMONEY
        toProtoEnumMay 36 = Hs.Just GatewayAIRTELMONEY
        toProtoEnumMay 37 = Hs.Just GatewayAMAZONPAY
        toProtoEnumMay 38 = Hs.Just GatewayPHONEPE
        toProtoEnumMay 39 = Hs.Just GatewaySTRIPE
        toProtoEnumMay 40 = Hs.Just GatewayDUMMY
        toProtoEnumMay 41 = Hs.Just GatewayHDFC_IVR
        toProtoEnumMay 42 = Hs.Just GatewayZESTMONEY
        toProtoEnumMay 43 = Hs.Just GatewayEPAYLATER
        toProtoEnumMay 44 = Hs.Just GatewayAXISNB
        toProtoEnumMay 45 = Hs.Just GatewayICICINB
        toProtoEnumMay 46 = Hs.Just GatewayTPSL_SI
        toProtoEnumMay 47 = Hs.Just GatewayAXIS_UPI
        toProtoEnumMay 48 = Hs.Just GatewayHDFC_UPI
        toProtoEnumMay 49 = Hs.Just GatewayINDUS_UPI
        toProtoEnumMay 50 = Hs.Just GatewayKOTAK_UPI
        toProtoEnumMay 51 = Hs.Just GatewaySBI_UPI
        toProtoEnumMay 52 = Hs.Just GatewayICICI_UPI
        toProtoEnumMay 53 = Hs.Just GatewayVIJAYA_UPI
        toProtoEnumMay 54 = Hs.Just GatewayHSBC_UPI
        toProtoEnumMay 55 = Hs.Just GatewayYESBANK_UPI
        toProtoEnumMay 56 = Hs.Just GatewayPAYTM_UPI
        toProtoEnumMay 57 = Hs.Just GatewayLINEPAY
        toProtoEnumMay 58 = Hs.Just GatewayOLAPOSTPAID
        toProtoEnumMay 59 = Hs.Just GatewaySIMPL
        toProtoEnumMay 60 = Hs.Just GatewayGOOGLEPAY
        toProtoEnumMay 61 = Hs.Just GatewayGOCASHFREE
        toProtoEnumMay 62 = Hs.Just GatewayPAYFORT
        toProtoEnumMay 63 = Hs.Just GatewayFSSPAY
        toProtoEnumMay 64 = Hs.Just GatewayCASH
        toProtoEnumMay 65 = Hs.Just GatewayMORPHEUS
        toProtoEnumMay 66 = Hs.Just GatewayFREECHARGE_V2
        toProtoEnumMay 67 = Hs.Just GatewayLAZYPAY
        toProtoEnumMay 68 = Hs.Just GatewayITZCASH
        toProtoEnumMay 69 = Hs.Just GatewayAXIS_BIZ
        toProtoEnumMay 70 = Hs.Just GatewayLOANTAP
        toProtoEnumMay 71 = Hs.Just GatewayDEFAULT
        toProtoEnumMay _ = Hs.Nothing
        fromProtoEnum (GatewayNO_GATEWAY) = 0
        fromProtoEnum (GatewayAXIS) = 1
        fromProtoEnum (GatewayHDFC) = 2
        fromProtoEnum (GatewayICICI) = 3
        fromProtoEnum (GatewayCITI) = 4
        fromProtoEnum (GatewayAMEX) = 5
        fromProtoEnum (GatewayCYBERSOURCE) = 6
        fromProtoEnum (GatewayIPG) = 7
        fromProtoEnum (GatewayMIGS) = 8
        fromProtoEnum (GatewayKOTAK) = 9
        fromProtoEnum (GatewayEBS) = 10
        fromProtoEnum (GatewayPAYU) = 11
        fromProtoEnum (GatewayCCAVENUE) = 12
        fromProtoEnum (GatewayCITRUS) = 13
        fromProtoEnum (GatewayATOM) = 14
        fromProtoEnum (GatewayCCAVENUE_V2) = 15
        fromProtoEnum (GatewayTPSL) = 16
        fromProtoEnum (GatewayPAYTM) = 17
        fromProtoEnum (GatewayPAYTM_V2) = 18
        fromProtoEnum (GatewayPAYPAL) = 19
        fromProtoEnum (GatewayHDFC_EBS_VAS) = 20
        fromProtoEnum (GatewayPAYLATER) = 21
        fromProtoEnum (GatewayRAZORPAY) = 22
        fromProtoEnum (GatewayFSS_ATM_PIN) = 23
        fromProtoEnum (GatewayEBS_V3) = 24
        fromProtoEnum (GatewayZAAKPAY) = 25
        fromProtoEnum (GatewayBILLDESK) = 26
        fromProtoEnum (GatewaySODEXO) = 27
        fromProtoEnum (GatewayBLAZEPAY) = 28
        fromProtoEnum (GatewayFSS_ATM_PIN_V2) = 29
        fromProtoEnum (GatewayMOBIKWIK) = 30
        fromProtoEnum (GatewayOLAMONEY) = 31
        fromProtoEnum (GatewayFREECHARGE) = 32
        fromProtoEnum (GatewayMPESA) = 33
        fromProtoEnum (GatewaySBIBUDDY) = 34
        fromProtoEnum (GatewayJIOMONEY) = 35
        fromProtoEnum (GatewayAIRTELMONEY) = 36
        fromProtoEnum (GatewayAMAZONPAY) = 37
        fromProtoEnum (GatewayPHONEPE) = 38
        fromProtoEnum (GatewaySTRIPE) = 39
        fromProtoEnum (GatewayDUMMY) = 40
        fromProtoEnum (GatewayHDFC_IVR) = 41
        fromProtoEnum (GatewayZESTMONEY) = 42
        fromProtoEnum (GatewayEPAYLATER) = 43
        fromProtoEnum (GatewayAXISNB) = 44
        fromProtoEnum (GatewayICICINB) = 45
        fromProtoEnum (GatewayTPSL_SI) = 46
        fromProtoEnum (GatewayAXIS_UPI) = 47
        fromProtoEnum (GatewayHDFC_UPI) = 48
        fromProtoEnum (GatewayINDUS_UPI) = 49
        fromProtoEnum (GatewayKOTAK_UPI) = 50
        fromProtoEnum (GatewaySBI_UPI) = 51
        fromProtoEnum (GatewayICICI_UPI) = 52
        fromProtoEnum (GatewayVIJAYA_UPI) = 53
        fromProtoEnum (GatewayHSBC_UPI) = 54
        fromProtoEnum (GatewayYESBANK_UPI) = 55
        fromProtoEnum (GatewayPAYTM_UPI) = 56
        fromProtoEnum (GatewayLINEPAY) = 57
        fromProtoEnum (GatewayOLAPOSTPAID) = 58
        fromProtoEnum (GatewaySIMPL) = 59
        fromProtoEnum (GatewayGOOGLEPAY) = 60
        fromProtoEnum (GatewayGOCASHFREE) = 61
        fromProtoEnum (GatewayPAYFORT) = 62
        fromProtoEnum (GatewayFSSPAY) = 63
        fromProtoEnum (GatewayCASH) = 64
        fromProtoEnum (GatewayMORPHEUS) = 65
        fromProtoEnum (GatewayFREECHARGE_V2) = 66
        fromProtoEnum (GatewayLAZYPAY) = 67
        fromProtoEnum (GatewayITZCASH) = 68
        fromProtoEnum (GatewayAXIS_BIZ) = 69
        fromProtoEnum (GatewayLOANTAP) = 70
        fromProtoEnum (GatewayDEFAULT) = 71
 
instance HsJSONPB.ToJSONPB Gateway where
        toJSONPB x _ = HsJSONPB.enumFieldString x
        toEncodingPB x _ = HsJSONPB.enumFieldEncoding x
 
instance HsJSONPB.FromJSONPB Gateway where
        parseJSONPB (HsJSONPB.String "NO_GATEWAY")
          = Hs.pure GatewayNO_GATEWAY
        parseJSONPB (HsJSONPB.String "AXIS") = Hs.pure GatewayAXIS
        parseJSONPB (HsJSONPB.String "HDFC") = Hs.pure GatewayHDFC
        parseJSONPB (HsJSONPB.String "ICICI") = Hs.pure GatewayICICI
        parseJSONPB (HsJSONPB.String "CITI") = Hs.pure GatewayCITI
        parseJSONPB (HsJSONPB.String "AMEX") = Hs.pure GatewayAMEX
        parseJSONPB (HsJSONPB.String "CYBERSOURCE")
          = Hs.pure GatewayCYBERSOURCE
        parseJSONPB (HsJSONPB.String "IPG") = Hs.pure GatewayIPG
        parseJSONPB (HsJSONPB.String "MIGS") = Hs.pure GatewayMIGS
        parseJSONPB (HsJSONPB.String "KOTAK") = Hs.pure GatewayKOTAK
        parseJSONPB (HsJSONPB.String "EBS") = Hs.pure GatewayEBS
        parseJSONPB (HsJSONPB.String "PAYU") = Hs.pure GatewayPAYU
        parseJSONPB (HsJSONPB.String "CCAVENUE") = Hs.pure GatewayCCAVENUE
        parseJSONPB (HsJSONPB.String "CITRUS") = Hs.pure GatewayCITRUS
        parseJSONPB (HsJSONPB.String "ATOM") = Hs.pure GatewayATOM
        parseJSONPB (HsJSONPB.String "CCAVENUE_V2")
          = Hs.pure GatewayCCAVENUE_V2
        parseJSONPB (HsJSONPB.String "TPSL") = Hs.pure GatewayTPSL
        parseJSONPB (HsJSONPB.String "PAYTM") = Hs.pure GatewayPAYTM
        parseJSONPB (HsJSONPB.String "PAYTM_V2") = Hs.pure GatewayPAYTM_V2
        parseJSONPB (HsJSONPB.String "PAYPAL") = Hs.pure GatewayPAYPAL
        parseJSONPB (HsJSONPB.String "HDFC_EBS_VAS")
          = Hs.pure GatewayHDFC_EBS_VAS
        parseJSONPB (HsJSONPB.String "PAYLATER") = Hs.pure GatewayPAYLATER
        parseJSONPB (HsJSONPB.String "RAZORPAY") = Hs.pure GatewayRAZORPAY
        parseJSONPB (HsJSONPB.String "FSS_ATM_PIN")
          = Hs.pure GatewayFSS_ATM_PIN
        parseJSONPB (HsJSONPB.String "EBS_V3") = Hs.pure GatewayEBS_V3
        parseJSONPB (HsJSONPB.String "ZAAKPAY") = Hs.pure GatewayZAAKPAY
        parseJSONPB (HsJSONPB.String "BILLDESK") = Hs.pure GatewayBILLDESK
        parseJSONPB (HsJSONPB.String "SODEXO") = Hs.pure GatewaySODEXO
        parseJSONPB (HsJSONPB.String "BLAZEPAY") = Hs.pure GatewayBLAZEPAY
        parseJSONPB (HsJSONPB.String "FSS_ATM_PIN_V2")
          = Hs.pure GatewayFSS_ATM_PIN_V2
        parseJSONPB (HsJSONPB.String "MOBIKWIK") = Hs.pure GatewayMOBIKWIK
        parseJSONPB (HsJSONPB.String "OLAMONEY") = Hs.pure GatewayOLAMONEY
        parseJSONPB (HsJSONPB.String "FREECHARGE")
          = Hs.pure GatewayFREECHARGE
        parseJSONPB (HsJSONPB.String "MPESA") = Hs.pure GatewayMPESA
        parseJSONPB (HsJSONPB.String "SBIBUDDY") = Hs.pure GatewaySBIBUDDY
        parseJSONPB (HsJSONPB.String "JIOMONEY") = Hs.pure GatewayJIOMONEY
        parseJSONPB (HsJSONPB.String "AIRTELMONEY")
          = Hs.pure GatewayAIRTELMONEY
        parseJSONPB (HsJSONPB.String "AMAZONPAY")
          = Hs.pure GatewayAMAZONPAY
        parseJSONPB (HsJSONPB.String "PHONEPE") = Hs.pure GatewayPHONEPE
        parseJSONPB (HsJSONPB.String "STRIPE") = Hs.pure GatewaySTRIPE
        parseJSONPB (HsJSONPB.String "DUMMY") = Hs.pure GatewayDUMMY
        parseJSONPB (HsJSONPB.String "HDFC_IVR") = Hs.pure GatewayHDFC_IVR
        parseJSONPB (HsJSONPB.String "ZESTMONEY")
          = Hs.pure GatewayZESTMONEY
        parseJSONPB (HsJSONPB.String "EPAYLATER")
          = Hs.pure GatewayEPAYLATER
        parseJSONPB (HsJSONPB.String "AXISNB") = Hs.pure GatewayAXISNB
        parseJSONPB (HsJSONPB.String "ICICINB") = Hs.pure GatewayICICINB
        parseJSONPB (HsJSONPB.String "TPSL_SI") = Hs.pure GatewayTPSL_SI
        parseJSONPB (HsJSONPB.String "AXIS_UPI") = Hs.pure GatewayAXIS_UPI
        parseJSONPB (HsJSONPB.String "HDFC_UPI") = Hs.pure GatewayHDFC_UPI
        parseJSONPB (HsJSONPB.String "INDUS_UPI")
          = Hs.pure GatewayINDUS_UPI
        parseJSONPB (HsJSONPB.String "KOTAK_UPI")
          = Hs.pure GatewayKOTAK_UPI
        parseJSONPB (HsJSONPB.String "SBI_UPI") = Hs.pure GatewaySBI_UPI
        parseJSONPB (HsJSONPB.String "ICICI_UPI")
          = Hs.pure GatewayICICI_UPI
        parseJSONPB (HsJSONPB.String "VIJAYA_UPI")
          = Hs.pure GatewayVIJAYA_UPI
        parseJSONPB (HsJSONPB.String "HSBC_UPI") = Hs.pure GatewayHSBC_UPI
        parseJSONPB (HsJSONPB.String "YESBANK_UPI")
          = Hs.pure GatewayYESBANK_UPI
        parseJSONPB (HsJSONPB.String "PAYTM_UPI")
          = Hs.pure GatewayPAYTM_UPI
        parseJSONPB (HsJSONPB.String "LINEPAY") = Hs.pure GatewayLINEPAY
        parseJSONPB (HsJSONPB.String "OLAPOSTPAID")
          = Hs.pure GatewayOLAPOSTPAID
        parseJSONPB (HsJSONPB.String "SIMPL") = Hs.pure GatewaySIMPL
        parseJSONPB (HsJSONPB.String "GOOGLEPAY")
          = Hs.pure GatewayGOOGLEPAY
        parseJSONPB (HsJSONPB.String "GOCASHFREE")
          = Hs.pure GatewayGOCASHFREE
        parseJSONPB (HsJSONPB.String "PAYFORT") = Hs.pure GatewayPAYFORT
        parseJSONPB (HsJSONPB.String "FSSPAY") = Hs.pure GatewayFSSPAY
        parseJSONPB (HsJSONPB.String "CASH") = Hs.pure GatewayCASH
        parseJSONPB (HsJSONPB.String "MORPHEUS") = Hs.pure GatewayMORPHEUS
        parseJSONPB (HsJSONPB.String "FREECHARGE_V2")
          = Hs.pure GatewayFREECHARGE_V2
        parseJSONPB (HsJSONPB.String "LAZYPAY") = Hs.pure GatewayLAZYPAY
        parseJSONPB (HsJSONPB.String "ITZCASH") = Hs.pure GatewayITZCASH
        parseJSONPB (HsJSONPB.String "AXIS_BIZ") = Hs.pure GatewayAXIS_BIZ
        parseJSONPB (HsJSONPB.String "LOANTAP") = Hs.pure GatewayLOANTAP
        parseJSONPB (HsJSONPB.String "DEFAULT") = Hs.pure GatewayDEFAULT
        parseJSONPB v = (HsJSONPB.typeMismatch "Gateway" v)
 
instance HsJSONPB.ToJSON Gateway where
        toJSON = HsJSONPB.toAesonValue
        toEncoding = HsJSONPB.toAesonEncoding
 
instance HsJSONPB.FromJSON Gateway where
        parseJSON = HsJSONPB.parseJSONPB
 
instance HsProtobuf.Finite Gateway
 
data TxnEventType = TxnEventTypeNO_TXN_EVENT
                  | TxnEventTypeTXN_EVENT_CREATE
                  | TxnEventTypeTXN_EVENT_UPDATE
                  deriving (Hs.Show, Hs.Eq, Hs.Generic, Hs.NFData)
 
instance HsProtobuf.Named TxnEventType where
        nameOf _ = (Hs.fromString "TxnEventType")
 
instance HsProtobuf.HasDefault TxnEventType
 
instance Hs.Bounded TxnEventType where
        minBound = TxnEventTypeNO_TXN_EVENT
        maxBound = TxnEventTypeTXN_EVENT_UPDATE
 
instance Hs.Ord TxnEventType where
        compare x y
          = Hs.compare (HsProtobuf.fromProtoEnum x)
              (HsProtobuf.fromProtoEnum y)
 
instance HsProtobuf.ProtoEnum TxnEventType where
        toProtoEnumMay 0 = Hs.Just TxnEventTypeNO_TXN_EVENT
        toProtoEnumMay 1 = Hs.Just TxnEventTypeTXN_EVENT_CREATE
        toProtoEnumMay 2 = Hs.Just TxnEventTypeTXN_EVENT_UPDATE
        toProtoEnumMay _ = Hs.Nothing
        fromProtoEnum (TxnEventTypeNO_TXN_EVENT) = 0
        fromProtoEnum (TxnEventTypeTXN_EVENT_CREATE) = 1
        fromProtoEnum (TxnEventTypeTXN_EVENT_UPDATE) = 2
 
instance HsJSONPB.ToJSONPB TxnEventType where
        toJSONPB x _ = HsJSONPB.enumFieldString x
        toEncodingPB x _ = HsJSONPB.enumFieldEncoding x
 
instance HsJSONPB.FromJSONPB TxnEventType where
        parseJSONPB (HsJSONPB.String "NO_TXN_EVENT")
          = Hs.pure TxnEventTypeNO_TXN_EVENT
        parseJSONPB (HsJSONPB.String "TXN_EVENT_CREATE")
          = Hs.pure TxnEventTypeTXN_EVENT_CREATE
        parseJSONPB (HsJSONPB.String "TXN_EVENT_UPDATE")
          = Hs.pure TxnEventTypeTXN_EVENT_UPDATE
        parseJSONPB v = (HsJSONPB.typeMismatch "TxnEventType" v)
 
instance HsJSONPB.ToJSON TxnEventType where
        toJSON = HsJSONPB.toAesonValue
        toEncoding = HsJSONPB.toAesonEncoding
 
instance HsJSONPB.FromJSON TxnEventType where
        parseJSON = HsJSONPB.parseJSONPB
 
instance HsProtobuf.Finite TxnEventType