# Autogenerated from euler.yaml. Do not edit.
# hash: 5f02a9ce0dbc2a070c05f3c799d0fbbde3c8e6d03f056f80120d910d69e538fa
# time: 2020-10-21 22:03:53.900150

self: super:
let
  euler-events-hs-src = super.eulerBuild.allowedPaths {
    root = ./..;
    paths = [
      ../euler-events-hs.cabal
      ../src
      ../test
    ];
  };
in 
super.eulerBuild.mkEulerHaskellOverlay self super
  (hself: hsuper: {
    prometheus-haskell = self.eulerBuild.fastBuildExternal {
      drv = hself.callCabal2nix "prometheus-haskell" (builtins.fetchTarball {
        url = "https://github.com/juspay/prometheus-haskell/archive/7bf933ad3e0059020273ab9d7fc799c582d663ae.tar.gz";
        sha256 = "1a00yb7258gk73idwffd2c1fvw6jci71mal143q81pgxaq9ivf78";
      }) { };
    };

    stm-containers = self.eulerBuild.fastBuildExternal {
      drv = super.haskell.lib.unmarkBroken hsuper.stm-containers;
    };

    list-t = self.eulerBuild.fastBuildExternal {
      drv = super.haskell.lib.unmarkBroken hsuper.list-t;
    };

    stm-hamt = self.eulerBuild.fastBuildExternal {
      drv = super.haskell.lib.unmarkBroken hsuper.stm-hamt;
    };

    primitive-extras = self.eulerBuild.fastBuildExternal {
      drv = super.haskell.lib.unmarkBroken hsuper.primitive-extras;
    };
    
    euler-events-hs = self.eulerBuild.fastBuild {
      drv = hself.callCabal2nix "euler-events-hs" euler-events-hs-src { };
      overrides = {
        # We want to run tests for our packages most of the time
        runTests = true;
      };
    };
  })
