# Autogenerated from euler.yaml. Do not edit.
# hash: 9c03370f22561c4f33b658b7d9301c101ed5d83b1b6b9fef13fdbcba6c8d925f
# time: 2020-10-21 21:53:14.611392

{
  description = "euler-events-hs";
  inputs = {
    # Laziness of nix allows us to be lazy hear and not to resolve deps
    # The downside is that most of this .follows are redundant
    
  };

  outputs = flakeInputs@{ self, euler-build, ... }:
    euler-build.mkEulerFlake {
      overlayPath = ./nix/overlay.nix;
      mkConfig = { nixpkgs }: {
        flakeName = "euler-events-hs";
        defaultPackageName = "euler-events-hs";
        exportPackages = [
          "euler-events-hs"
        ];
        shellTools = with nixpkgs; [
          
        ];
        # shellAttrs = {
        # };
      };
      inputs = flakeInputs;
    };
}
