resolver: lts-20.18

packages:
- .

system-ghc: true

extra-deps:
  - git: https://github.com/juspay/prometheus-haskell
    commit: 1104a429745c45f333508c7aa2cd7d6f94b76755
    subdirs:
      - prometheus-client
      - prometheus-metrics-ghc
      - prometheus-proc
      - wai-middleware-prometheus

  # needed by prometheus-haskell
  - unix-memory-0.1.2@sha256:601231a46e84088103190a156c1919573237317e7d4f775cd555c54356e0e2c4,1269
