module Euler.Events.Types.Metric where

import Data.Text (Text)

data MetricOperation a
  = ReadyUp
  | ReadyDown (MetricResult a)
  | Increment Text -- Increment <counterName>
  | Set Text Double -- Set <gaugeName> <value>
  | RegisterVector1Counter Text Text -- RegisterVector1Counter <vectorName> <labelName>
  | IncrementVector1Counter Text Text -- IncrementVector1Counter <vectorName> <labelValue>

data MetricResult a
  = ReadyUpResult a
  | ReadyDownResult
  | Incremented
  | Setted
  | RegisteredVector1Counter
  | IncrementedVector1Counter
  | MetricResultError


data MetricKey
  = EXTERNAL_API_CALL
  | TXNS_CARD_STORED
  | TXNS_START
  | INVALID_REQUEST
  | TXNS_STATUS
  | TXNS_PROXIED_TO_EC
  | DB_FETCH_FAILURE
  | CLIENT_AUTH_TOKEN_GENERATED
  | REFUND_DECODE_ERROR
  | REFUND_INVALID_REQUEST
  | REFUND_RECEIVED_EULER
  | REFUND_FORWARDED_EC
  | WALLET_FORWARDED_EC
  | REFUND_INITIATED
  | REFUND_TRIGGERED
  | REFUND_SUCCESS
  | REFUND_FAILURE
  | REFUND_WEBHOOK_INITIATED
  | REFUND_WEBHOOK_SUCCESS
  | REFUND_WEBHOOK_FAILURE
  | ORDER_STATUS_CACHE_ADD
  | ORDER_STATUS_CACHE_MISS
  | ORDER_STATUS_CACHE_HIT
  | DB_SYNC_DELAY
  | DB_SYNC_ERROR
  | DB_SYNC_BATCH_SIZE
  | DB_SYNC_COMMAND_COUNT
  | DB_SYNC_DIRTY_CMD
  | DB_SYNC_UNIQUE_CONSTRAINT_ERROR
  | DB_SYNC_PROCESS_TIME
  | DB_SYNC_STREAM_LENGTH
  | UPI_WEBHOOK_FORWARDED_COUNT
  | UPI_WEBHOOK_RECEIVED_COUNT
  | UPI_WEBHOOK_SUCCESS_COUNT
  | EULER_ORDER_STATUS_COUNT
  | EC_ORDER_STATUS_COUNT
  | EULER_ORDER_STATUS_MISMATCH_COUNT
  | AUTO_REFUNDED_TRANSACTIONS
  | STATUS_FORCE_SYNC
  | FORCE_SYNC_FAIL
  | VIES_CYBS_PA_ENROLL_FAILURE
  | VIES_CYBS_PA_ENROLL_SUCCESS
  | VIES_CYBS_PA_VALIDATE_SUCCESS
  | VIES_CYBS_PA_VALIDATE_FAILED
  | MEM_CACHE_HIT
  | MEM_CACHE_MISS
  | MEM_CACHE_RELOAD
  | GATEWAY_SCORE
  | TOTAL_LOCKS_ACQUIRED
  | TOTAL_REQUESTS_REJECTED
  deriving (Show, Read, Eq, Ord)
